// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: proto/systemtest.proto

package systemtestpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinatorService_TakeLease_FullMethodName    = "/systemtest.v1.CoordinatorService/TakeLease"
	CoordinatorService_Keepalive_FullMethodName    = "/systemtest.v1.CoordinatorService/Keepalive"
	CoordinatorService_ReleaseLease_FullMethodName = "/systemtest.v1.CoordinatorService/ReleaseLease"
	CoordinatorService_Status_FullMethodName       = "/systemtest.v1.CoordinatorService/Status"
)

// CoordinatorServiceClient is the client API for CoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorServiceClient interface {
	TakeLease(ctx context.Context, in *TakeLeaseRequest, opts ...grpc.CallOption) (*TakeLeaseResponse, error)
	Keepalive(ctx context.Context, in *KeepaliveRequest, opts ...grpc.CallOption) (*KeepaliveResponse, error)
	ReleaseLease(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type coordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorServiceClient(cc grpc.ClientConnInterface) CoordinatorServiceClient {
	return &coordinatorServiceClient{cc}
}

func (c *coordinatorServiceClient) TakeLease(ctx context.Context, in *TakeLeaseRequest, opts ...grpc.CallOption) (*TakeLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeLeaseResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_TakeLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) Keepalive(ctx context.Context, in *KeepaliveRequest, opts ...grpc.CallOption) (*KeepaliveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeepaliveResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_Keepalive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ReleaseLease(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_ReleaseLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServiceServer is the server API for CoordinatorService service.
// All implementations should embed UnimplementedCoordinatorServiceServer
// for forward compatibility.
type CoordinatorServiceServer interface {
	TakeLease(context.Context, *TakeLeaseRequest) (*TakeLeaseResponse, error)
	Keepalive(context.Context, *KeepaliveRequest) (*KeepaliveResponse, error)
	ReleaseLease(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
}

// UnimplementedCoordinatorServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServiceServer struct{}

func (UnimplementedCoordinatorServiceServer) TakeLease(context.Context, *TakeLeaseRequest) (*TakeLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeLease not implemented")
}
func (UnimplementedCoordinatorServiceServer) Keepalive(context.Context, *KeepaliveRequest) (*KeepaliveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Keepalive not implemented")
}
func (UnimplementedCoordinatorServiceServer) ReleaseLease(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseLease not implemented")
}
func (UnimplementedCoordinatorServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedCoordinatorServiceServer) testEmbeddedByValue() {}

// UnsafeCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServiceServer will
// result in compilation errors.
type UnsafeCoordinatorServiceServer interface {
	mustEmbedUnimplementedCoordinatorServiceServer()
}

func RegisterCoordinatorServiceServer(s grpc.ServiceRegistrar, srv CoordinatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoordinatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinatorService_ServiceDesc, srv)
}

func _CoordinatorService_TakeLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).TakeLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_TakeLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).TakeLease(ctx, req.(*TakeLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_Keepalive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepaliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Keepalive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_Keepalive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Keepalive(ctx, req.(*KeepaliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ReleaseLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ReleaseLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ReleaseLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ReleaseLease(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinatorService_ServiceDesc is the grpc.ServiceDesc for CoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "systemtest.v1.CoordinatorService",
	HandlerType: (*CoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TakeLease",
			Handler:    _CoordinatorService_TakeLease_Handler,
		},
		{
			MethodName: "Keepalive",
			Handler:    _CoordinatorService_Keepalive_Handler,
		},
		{
			MethodName: "ReleaseLease",
			Handler:    _CoordinatorService_ReleaseLease_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _CoordinatorService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/systemtest.proto",
}

const (
	CoordinatorPlugin_DescribePlugin_FullMethodName      = "/systemtest.v1.CoordinatorPlugin/DescribePlugin"
	CoordinatorPlugin_GetResourcePool_FullMethodName     = "/systemtest.v1.CoordinatorPlugin/GetResourcePool"
	CoordinatorPlugin_GetResourceRequests_FullMethodName = "/systemtest.v1.CoordinatorPlugin/GetResourceRequests"
	CoordinatorPlugin_CreateFixture_FullMethodName       = "/systemtest.v1.CoordinatorPlugin/CreateFixture"
	CoordinatorPlugin_DestroyFixture_FullMethodName      = "/systemtest.v1.CoordinatorPlugin/DestroyFixture"
	CoordinatorPlugin_HealthCheck_FullMethodName         = "/systemtest.v1.CoordinatorPlugin/HealthCheck"
)

// CoordinatorPluginClient is the client API for CoordinatorPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorPluginClient interface {
	DescribePlugin(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DescribeResponses, error)
	GetResourcePool(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*ResourcePool, error)
	GetResourceRequests(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*ResourceRequests, error)
	CreateFixture(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateProgress], error)
	DestroyFixture(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type coordinatorPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorPluginClient(cc grpc.ClientConnInterface) CoordinatorPluginClient {
	return &coordinatorPluginClient{cc}
}

func (c *coordinatorPluginClient) DescribePlugin(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DescribeResponses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponses)
	err := c.cc.Invoke(ctx, CoordinatorPlugin_DescribePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorPluginClient) GetResourcePool(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*ResourcePool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcePool)
	err := c.cc.Invoke(ctx, CoordinatorPlugin_GetResourcePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorPluginClient) GetResourceRequests(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*ResourceRequests, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceRequests)
	err := c.cc.Invoke(ctx, CoordinatorPlugin_GetResourceRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorPluginClient) CreateFixture(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoordinatorPlugin_ServiceDesc.Streams[0], CoordinatorPlugin_CreateFixture_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateRequest, CreateProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorPlugin_CreateFixtureClient = grpc.ServerStreamingClient[CreateProgress]

func (c *coordinatorPluginClient) DestroyFixture(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyResponse)
	err := c.cc.Invoke(ctx, CoordinatorPlugin_DestroyFixture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorPluginClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, CoordinatorPlugin_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorPluginServer is the server API for CoordinatorPlugin service.
// All implementations should embed UnimplementedCoordinatorPluginServer
// for forward compatibility.
type CoordinatorPluginServer interface {
	DescribePlugin(context.Context, *Empty) (*DescribeResponses, error)
	GetResourcePool(context.Context, *CreateRequest) (*ResourcePool, error)
	GetResourceRequests(context.Context, *CreateRequest) (*ResourceRequests, error)
	CreateFixture(*CreateRequest, grpc.ServerStreamingServer[CreateProgress]) error
	DestroyFixture(context.Context, *DestroyRequest) (*DestroyResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

// UnimplementedCoordinatorPluginServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorPluginServer struct{}

func (UnimplementedCoordinatorPluginServer) DescribePlugin(context.Context, *Empty) (*DescribeResponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribePlugin not implemented")
}
func (UnimplementedCoordinatorPluginServer) GetResourcePool(context.Context, *CreateRequest) (*ResourcePool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourcePool not implemented")
}
func (UnimplementedCoordinatorPluginServer) GetResourceRequests(context.Context, *CreateRequest) (*ResourceRequests, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceRequests not implemented")
}
func (UnimplementedCoordinatorPluginServer) CreateFixture(*CreateRequest, grpc.ServerStreamingServer[CreateProgress]) error {
	return status.Errorf(codes.Unimplemented, "method CreateFixture not implemented")
}
func (UnimplementedCoordinatorPluginServer) DestroyFixture(context.Context, *DestroyRequest) (*DestroyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyFixture not implemented")
}
func (UnimplementedCoordinatorPluginServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCoordinatorPluginServer) testEmbeddedByValue() {}

// UnsafeCoordinatorPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorPluginServer will
// result in compilation errors.
type UnsafeCoordinatorPluginServer interface {
	mustEmbedUnimplementedCoordinatorPluginServer()
}

func RegisterCoordinatorPluginServer(s grpc.ServiceRegistrar, srv CoordinatorPluginServer) {
	// If the following call pancis, it indicates UnimplementedCoordinatorPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinatorPlugin_ServiceDesc, srv)
}

func _CoordinatorPlugin_DescribePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorPluginServer).DescribePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorPlugin_DescribePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorPluginServer).DescribePlugin(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorPlugin_GetResourcePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorPluginServer).GetResourcePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorPlugin_GetResourcePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorPluginServer).GetResourcePool(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorPlugin_GetResourceRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorPluginServer).GetResourceRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorPlugin_GetResourceRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorPluginServer).GetResourceRequests(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorPlugin_CreateFixture_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoordinatorPluginServer).CreateFixture(m, &grpc.GenericServerStream[CreateRequest, CreateProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorPlugin_CreateFixtureServer = grpc.ServerStreamingServer[CreateProgress]

func _CoordinatorPlugin_DestroyFixture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorPluginServer).DestroyFixture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorPlugin_DestroyFixture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorPluginServer).DestroyFixture(ctx, req.(*DestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorPlugin_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorPluginServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorPlugin_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorPluginServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinatorPlugin_ServiceDesc is the grpc.ServiceDesc for CoordinatorPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "systemtest.v1.CoordinatorPlugin",
	HandlerType: (*CoordinatorPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribePlugin",
			Handler:    _CoordinatorPlugin_DescribePlugin_Handler,
		},
		{
			MethodName: "GetResourcePool",
			Handler:    _CoordinatorPlugin_GetResourcePool_Handler,
		},
		{
			MethodName: "GetResourceRequests",
			Handler:    _CoordinatorPlugin_GetResourceRequests_Handler,
		},
		{
			MethodName: "DestroyFixture",
			Handler:    _CoordinatorPlugin_DestroyFixture_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CoordinatorPlugin_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateFixture",
			Handler:       _CoordinatorPlugin_CreateFixture_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/systemtest.proto",
}
