// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: proto/systemtest.proto

package systemtestpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaseStatus int32

const (
	LeaseStatus_LEASE_STATUS_UNKNOWN LeaseStatus = 0
	LeaseStatus_PENDING              LeaseStatus = 1
	LeaseStatus_SUCCEEDED            LeaseStatus = 2
	LeaseStatus_FAILED               LeaseStatus = 3
)

// Enum value maps for LeaseStatus.
var (
	LeaseStatus_name = map[int32]string{
		0: "LEASE_STATUS_UNKNOWN",
		1: "PENDING",
		2: "SUCCEEDED",
		3: "FAILED",
	}
	LeaseStatus_value = map[string]int32{
		"LEASE_STATUS_UNKNOWN": 0,
		"PENDING":              1,
		"SUCCEEDED":            2,
		"FAILED":               3,
	}
)

func (x LeaseStatus) Enum() *LeaseStatus {
	p := new(LeaseStatus)
	*p = x
	return p
}

func (x LeaseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_systemtest_proto_enumTypes[0].Descriptor()
}

func (LeaseStatus) Type() protoreflect.EnumType {
	return &file_proto_systemtest_proto_enumTypes[0]
}

func (x LeaseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaseStatus.Descriptor instead.
func (LeaseStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{0}
}

type CreateProgressStatus int32

const (
	CreateProgressStatus_CREATE_PROGRESS_UNKNOWN   CreateProgressStatus = 0
	CreateProgressStatus_CREATE_PROGRESS_ENQUEUED  CreateProgressStatus = 1
	CreateProgressStatus_CREATE_PROGRESS_CREATING  CreateProgressStatus = 2
	CreateProgressStatus_CREATE_PROGRESS_RUNNING   CreateProgressStatus = 3
	CreateProgressStatus_CREATE_PROGRESS_SUCCEEDED CreateProgressStatus = 4
	CreateProgressStatus_CREATE_PROGRESS_ERROR     CreateProgressStatus = 5
)

// Enum value maps for CreateProgressStatus.
var (
	CreateProgressStatus_name = map[int32]string{
		0: "CREATE_PROGRESS_UNKNOWN",
		1: "CREATE_PROGRESS_ENQUEUED",
		2: "CREATE_PROGRESS_CREATING",
		3: "CREATE_PROGRESS_RUNNING",
		4: "CREATE_PROGRESS_SUCCEEDED",
		5: "CREATE_PROGRESS_ERROR",
	}
	CreateProgressStatus_value = map[string]int32{
		"CREATE_PROGRESS_UNKNOWN":   0,
		"CREATE_PROGRESS_ENQUEUED":  1,
		"CREATE_PROGRESS_CREATING":  2,
		"CREATE_PROGRESS_RUNNING":   3,
		"CREATE_PROGRESS_SUCCEEDED": 4,
		"CREATE_PROGRESS_ERROR":     5,
	}
)

func (x CreateProgressStatus) Enum() *CreateProgressStatus {
	p := new(CreateProgressStatus)
	*p = x
	return p
}

func (x CreateProgressStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateProgressStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_systemtest_proto_enumTypes[1].Descriptor()
}

func (CreateProgressStatus) Type() protoreflect.EnumType {
	return &file_proto_systemtest_proto_enumTypes[1]
}

func (x CreateProgressStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateProgressStatus.Descriptor instead.
func (CreateProgressStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{1}
}

type FixtureElementStatus int32

const (
	FixtureElementStatus_FIXTURE_ELEMENT_UNKNOWN  FixtureElementStatus = 0
	FixtureElementStatus_FIXTURE_ELEMENT_CREATING FixtureElementStatus = 1
	FixtureElementStatus_FIXTURE_ELEMENT_RUNNING  FixtureElementStatus = 2
	FixtureElementStatus_FIXTURE_ELEMENT_ERROR    FixtureElementStatus = 3
)

// Enum value maps for FixtureElementStatus.
var (
	FixtureElementStatus_name = map[int32]string{
		0: "FIXTURE_ELEMENT_UNKNOWN",
		1: "FIXTURE_ELEMENT_CREATING",
		2: "FIXTURE_ELEMENT_RUNNING",
		3: "FIXTURE_ELEMENT_ERROR",
	}
	FixtureElementStatus_value = map[string]int32{
		"FIXTURE_ELEMENT_UNKNOWN":  0,
		"FIXTURE_ELEMENT_CREATING": 1,
		"FIXTURE_ELEMENT_RUNNING":  2,
		"FIXTURE_ELEMENT_ERROR":    3,
	}
)

func (x FixtureElementStatus) Enum() *FixtureElementStatus {
	p := new(FixtureElementStatus)
	*p = x
	return p
}

func (x FixtureElementStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FixtureElementStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_systemtest_proto_enumTypes[2].Descriptor()
}

func (FixtureElementStatus) Type() protoreflect.EnumType {
	return &file_proto_systemtest_proto_enumTypes[2]
}

func (x FixtureElementStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FixtureElementStatus.Descriptor instead.
func (FixtureElementStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{2}
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_Str
	//	*Value_Data
	//	*Value_SchemaBlob_
	//	*Value_IntValue
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_proto_systemtest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetStr() string {
	if x != nil {
		if x, ok := x.Value.(*Value_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *Value) GetData() []byte {
	if x != nil {
		if x, ok := x.Value.(*Value_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Value) GetSchemaBlob() *Value_SchemaBlob {
	if x != nil {
		if x, ok := x.Value.(*Value_SchemaBlob_); ok {
			return x.SchemaBlob
		}
	}
	return nil
}

func (x *Value) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

type isValue_Value interface {
	isValue_Value()
}

type Value_Str struct {
	Str string `protobuf:"bytes,1,opt,name=str,proto3,oneof"`
}

type Value_Data struct {
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type Value_SchemaBlob_ struct {
	SchemaBlob *Value_SchemaBlob `protobuf:"bytes,4,opt,name=schema_blob,json=schemaBlob,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int32 `protobuf:"varint,5,opt,name=int_value,json=intValue,proto3,oneof"`
}

func (*Value_Str) isValue_Value() {}

func (*Value_Data) isValue_Value() {}

func (*Value_SchemaBlob_) isValue_Value() {}

func (*Value_IntValue) isValue_Value() {}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_systemtest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{1}
}

type Sharing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to UseScope:
	//
	//	*Sharing_Unrestricted
	//	*Sharing_ClientRestricted
	//	*Sharing_SingleUse
	UseScope                     isSharing_UseScope `protobuf_oneof:"use_scope"`
	MaximumConcurrentConnections int64              `protobuf:"varint,4,opt,name=maximum_concurrent_connections,json=maximumConcurrentConnections,proto3" json:"maximum_concurrent_connections,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Sharing) Reset() {
	*x = Sharing{}
	mi := &file_proto_systemtest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sharing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sharing) ProtoMessage() {}

func (x *Sharing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sharing.ProtoReflect.Descriptor instead.
func (*Sharing) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{2}
}

func (x *Sharing) GetUseScope() isSharing_UseScope {
	if x != nil {
		return x.UseScope
	}
	return nil
}

func (x *Sharing) GetUnrestricted() *Empty {
	if x != nil {
		if x, ok := x.UseScope.(*Sharing_Unrestricted); ok {
			return x.Unrestricted
		}
	}
	return nil
}

func (x *Sharing) GetClientRestricted() *Empty {
	if x != nil {
		if x, ok := x.UseScope.(*Sharing_ClientRestricted); ok {
			return x.ClientRestricted
		}
	}
	return nil
}

func (x *Sharing) GetSingleUse() *Empty {
	if x != nil {
		if x, ok := x.UseScope.(*Sharing_SingleUse); ok {
			return x.SingleUse
		}
	}
	return nil
}

func (x *Sharing) GetMaximumConcurrentConnections() int64 {
	if x != nil {
		return x.MaximumConcurrentConnections
	}
	return 0
}

type isSharing_UseScope interface {
	isSharing_UseScope()
}

type Sharing_Unrestricted struct {
	Unrestricted *Empty `protobuf:"bytes,1,opt,name=unrestricted,proto3,oneof"`
}

type Sharing_ClientRestricted struct {
	ClientRestricted *Empty `protobuf:"bytes,2,opt,name=client_restricted,json=clientRestricted,proto3,oneof"`
}

type Sharing_SingleUse struct {
	SingleUse *Empty `protobuf:"bytes,3,opt,name=single_use,json=singleUse,proto3,oneof"`
}

func (*Sharing_Unrestricted) isSharing_UseScope() {}

func (*Sharing_ClientRestricted) isSharing_UseScope() {}

func (*Sharing_SingleUse) isSharing_UseScope() {}

type FixtureDescription struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ImplId string                 `protobuf:"bytes,1,opt,name=impl_id,json=implId,proto3" json:"impl_id,omitempty"`
	// Types that are valid to be assigned to Plugin:
	//
	//	*FixtureDescription_BinaryPath
	//	*FixtureDescription_ContainerRef
	Plugin                isFixtureDescription_Plugin `protobuf_oneof:"plugin"`
	Inputs                map[string]*Value           `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ImageInputs           []string                    `protobuf:"bytes,5,rep,name=image_inputs,json=imageInputs,proto3" json:"image_inputs,omitempty"`
	FileInputs            []string                    `protobuf:"bytes,6,rep,name=file_inputs,json=fileInputs,proto3" json:"file_inputs,omitempty"`
	Sharing               *Sharing                    `protobuf:"bytes,7,opt,name=sharing,proto3" json:"sharing,omitempty"`
	StartupTimeoutSeconds int64                       `protobuf:"varint,8,opt,name=startup_timeout_seconds,json=startupTimeoutSeconds,proto3" json:"startup_timeout_seconds,omitempty"`
	Name                  string                      `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FixtureDescription) Reset() {
	*x = FixtureDescription{}
	mi := &file_proto_systemtest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixtureDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixtureDescription) ProtoMessage() {}

func (x *FixtureDescription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixtureDescription.ProtoReflect.Descriptor instead.
func (*FixtureDescription) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{3}
}

func (x *FixtureDescription) GetImplId() string {
	if x != nil {
		return x.ImplId
	}
	return ""
}

func (x *FixtureDescription) GetPlugin() isFixtureDescription_Plugin {
	if x != nil {
		return x.Plugin
	}
	return nil
}

func (x *FixtureDescription) GetBinaryPath() string {
	if x != nil {
		if x, ok := x.Plugin.(*FixtureDescription_BinaryPath); ok {
			return x.BinaryPath
		}
	}
	return ""
}

func (x *FixtureDescription) GetContainerRef() string {
	if x != nil {
		if x, ok := x.Plugin.(*FixtureDescription_ContainerRef); ok {
			return x.ContainerRef
		}
	}
	return ""
}

func (x *FixtureDescription) GetInputs() map[string]*Value {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *FixtureDescription) GetImageInputs() []string {
	if x != nil {
		return x.ImageInputs
	}
	return nil
}

func (x *FixtureDescription) GetFileInputs() []string {
	if x != nil {
		return x.FileInputs
	}
	return nil
}

func (x *FixtureDescription) GetSharing() *Sharing {
	if x != nil {
		return x.Sharing
	}
	return nil
}

func (x *FixtureDescription) GetStartupTimeoutSeconds() int64 {
	if x != nil {
		return x.StartupTimeoutSeconds
	}
	return 0
}

func (x *FixtureDescription) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type isFixtureDescription_Plugin interface {
	isFixtureDescription_Plugin()
}

type FixtureDescription_BinaryPath struct {
	BinaryPath string `protobuf:"bytes,2,opt,name=binary_path,json=binaryPath,proto3,oneof"`
}

type FixtureDescription_ContainerRef struct {
	ContainerRef string `protobuf:"bytes,3,opt,name=container_ref,json=containerRef,proto3,oneof"`
}

func (*FixtureDescription_BinaryPath) isFixtureDescription_Plugin() {}

func (*FixtureDescription_ContainerRef) isFixtureDescription_Plugin() {}

type TakeLeaseRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Fixture              *FixtureDescription    `protobuf:"bytes,1,opt,name=fixture,proto3" json:"fixture,omitempty"`
	ClientId             string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Owner                string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	TtlSeconds           int64                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	AssociatedTestsCount uint32                 `protobuf:"varint,5,opt,name=associated_tests_count,json=associatedTestsCount,proto3" json:"associated_tests_count,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TakeLeaseRequest) Reset() {
	*x = TakeLeaseRequest{}
	mi := &file_proto_systemtest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeLeaseRequest) ProtoMessage() {}

func (x *TakeLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeLeaseRequest.ProtoReflect.Descriptor instead.
func (*TakeLeaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{4}
}

func (x *TakeLeaseRequest) GetFixture() *FixtureDescription {
	if x != nil {
		return x.Fixture
	}
	return nil
}

func (x *TakeLeaseRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TakeLeaseRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TakeLeaseRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *TakeLeaseRequest) GetAssociatedTestsCount() uint32 {
	if x != nil {
		return x.AssociatedTestsCount
	}
	return 0
}

type TakeLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        LeaseStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=systemtest.v1.LeaseStatus" json:"status,omitempty"`
	LeaseId       string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Outputs       map[string]*Value      `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Messages      []string               `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeLeaseResponse) Reset() {
	*x = TakeLeaseResponse{}
	mi := &file_proto_systemtest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeLeaseResponse) ProtoMessage() {}

func (x *TakeLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeLeaseResponse.ProtoReflect.Descriptor instead.
func (*TakeLeaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{5}
}

func (x *TakeLeaseResponse) GetStatus() LeaseStatus {
	if x != nil {
		return x.Status
	}
	return LeaseStatus_LEASE_STATUS_UNKNOWN
}

func (x *TakeLeaseResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *TakeLeaseResponse) GetOutputs() map[string]*Value {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *TakeLeaseResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

type KeepaliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepaliveRequest) Reset() {
	*x = KeepaliveRequest{}
	mi := &file_proto_systemtest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepaliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepaliveRequest) ProtoMessage() {}

func (x *KeepaliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepaliveRequest.ProtoReflect.Descriptor instead.
func (*KeepaliveRequest) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{6}
}

func (x *KeepaliveRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type KeepaliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepaliveResponse) Reset() {
	*x = KeepaliveResponse{}
	mi := &file_proto_systemtest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepaliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepaliveResponse) ProtoMessage() {}

func (x *KeepaliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepaliveResponse.ProtoReflect.Descriptor instead.
func (*KeepaliveResponse) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{7}
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_proto_systemtest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_proto_systemtest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{9}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_systemtest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{10}
}

func (x *StatusRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        LeaseStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=systemtest.v1.LeaseStatus" json:"status,omitempty"`
	Outputs       map[string]*Value      `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Messages      []string               `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_systemtest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{11}
}

func (x *StatusResponse) GetStatus() LeaseStatus {
	if x != nil {
		return x.Status
	}
	return LeaseStatus_LEASE_STATUS_UNKNOWN
}

func (x *StatusResponse) GetOutputs() map[string]*Value {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *StatusResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

type DescribeResponses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*DescribeResponse    `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponses) Reset() {
	*x = DescribeResponses{}
	mi := &file_proto_systemtest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponses) ProtoMessage() {}

func (x *DescribeResponses) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponses.ProtoReflect.Descriptor instead.
func (*DescribeResponses) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{12}
}

func (x *DescribeResponses) GetResponses() []*DescribeResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type DescribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImplId        string                 `protobuf:"bytes,1,opt,name=impl_id,json=implId,proto3" json:"impl_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Schemas       map[string]string      `protobuf:"bytes,3,rep,name=schemas,proto3" json:"schemas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_proto_systemtest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{13}
}

func (x *DescribeResponse) GetImplId() string {
	if x != nil {
		return x.ImplId
	}
	return ""
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeResponse) GetSchemas() map[string]string {
	if x != nil {
		return x.Schemas
	}
	return nil
}

type CreationMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FixtureId     string                 `protobuf:"bytes,1,opt,name=fixture_id,json=fixtureId,proto3" json:"fixture_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreationMetadata) Reset() {
	*x = CreationMetadata{}
	mi := &file_proto_systemtest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreationMetadata) ProtoMessage() {}

func (x *CreationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreationMetadata.ProtoReflect.Descriptor instead.
func (*CreationMetadata) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{14}
}

func (x *CreationMetadata) GetFixtureId() string {
	if x != nil {
		return x.FixtureId
	}
	return ""
}

func (x *CreationMetadata) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreationMetadata) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreationMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImplId        string                 `protobuf:"bytes,1,opt,name=impl_id,json=implId,proto3" json:"impl_id,omitempty"`
	Inputs        map[string]*Value      `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      *CreationMetadata      `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_systemtest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{15}
}

func (x *CreateRequest) GetImplId() string {
	if x != nil {
		return x.ImplId
	}
	return ""
}

func (x *CreateRequest) GetInputs() map[string]*Value {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *CreateRequest) GetMetadata() *CreationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ResourceAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceAmount) Reset() {
	*x = ResourceAmount{}
	mi := &file_proto_systemtest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAmount) ProtoMessage() {}

func (x *ResourceAmount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceAmount.ProtoReflect.Descriptor instead.
func (*ResourceAmount) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{16}
}

func (x *ResourceAmount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceAmount) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ResourceAmount) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ResourcePool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Resources     []*ResourceAmount      `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcePool) Reset() {
	*x = ResourcePool{}
	mi := &file_proto_systemtest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcePool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcePool) ProtoMessage() {}

func (x *ResourcePool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcePool.ProtoReflect.Descriptor instead.
func (*ResourcePool) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{17}
}

func (x *ResourcePool) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *ResourcePool) GetResources() []*ResourceAmount {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ResourceRequests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consumes      []*ResourcePool        `protobuf:"bytes,1,rep,name=consumes,proto3" json:"consumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequests) Reset() {
	*x = ResourceRequests{}
	mi := &file_proto_systemtest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequests) ProtoMessage() {}

func (x *ResourceRequests) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequests.ProtoReflect.Descriptor instead.
func (*ResourceRequests) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{18}
}

func (x *ResourceRequests) GetConsumes() []*ResourcePool {
	if x != nil {
		return x.Consumes
	}
	return nil
}

type FixtureElementStatusInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementName   string                 `protobuf:"bytes,1,opt,name=element_name,json=elementName,proto3" json:"element_name,omitempty"`
	Status        FixtureElementStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=systemtest.v1.FixtureElementStatus" json:"status,omitempty"`
	Messages      []string               `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixtureElementStatusInfo) Reset() {
	*x = FixtureElementStatusInfo{}
	mi := &file_proto_systemtest_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixtureElementStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixtureElementStatusInfo) ProtoMessage() {}

func (x *FixtureElementStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixtureElementStatusInfo.ProtoReflect.Descriptor instead.
func (*FixtureElementStatusInfo) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{19}
}

func (x *FixtureElementStatusInfo) GetElementName() string {
	if x != nil {
		return x.ElementName
	}
	return ""
}

func (x *FixtureElementStatusInfo) GetStatus() FixtureElementStatus {
	if x != nil {
		return x.Status
	}
	return FixtureElementStatus_FIXTURE_ELEMENT_UNKNOWN
}

func (x *FixtureElementStatusInfo) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

type CreateProgress struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        CreateProgressStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=systemtest.v1.CreateProgressStatus" json:"status,omitempty"`
	ElementInfos  []*FixtureElementStatusInfo `protobuf:"bytes,2,rep,name=element_infos,json=elementInfos,proto3" json:"element_infos,omitempty"`
	Result        *FixtureResult              `protobuf:"bytes,3,opt,name=result,proto3,oneof" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProgress) Reset() {
	*x = CreateProgress{}
	mi := &file_proto_systemtest_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProgress) ProtoMessage() {}

func (x *CreateProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProgress.ProtoReflect.Descriptor instead.
func (*CreateProgress) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{20}
}

func (x *CreateProgress) GetStatus() CreateProgressStatus {
	if x != nil {
		return x.Status
	}
	return CreateProgressStatus_CREATE_PROGRESS_UNKNOWN
}

func (x *CreateProgress) GetElementInfos() []*FixtureElementStatusInfo {
	if x != nil {
		return x.ElementInfos
	}
	return nil
}

func (x *CreateProgress) GetResult() *FixtureResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type FixtureResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Outputs            map[string]*Value      `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IdleTimeoutSeconds int64                  `protobuf:"varint,2,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3" json:"idle_timeout_seconds,omitempty"`
	InstanceData       []byte                 `protobuf:"bytes,3,opt,name=instance_data,json=instanceData,proto3" json:"instance_data,omitempty"`
	Consumed           []*ResourcePool        `protobuf:"bytes,4,rep,name=consumed,proto3" json:"consumed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FixtureResult) Reset() {
	*x = FixtureResult{}
	mi := &file_proto_systemtest_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixtureResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixtureResult) ProtoMessage() {}

func (x *FixtureResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixtureResult.ProtoReflect.Descriptor instead.
func (*FixtureResult) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{21}
}

func (x *FixtureResult) GetOutputs() map[string]*Value {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *FixtureResult) GetIdleTimeoutSeconds() int64 {
	if x != nil {
		return x.IdleTimeoutSeconds
	}
	return 0
}

func (x *FixtureResult) GetInstanceData() []byte {
	if x != nil {
		return x.InstanceData
	}
	return nil
}

func (x *FixtureResult) GetConsumed() []*ResourcePool {
	if x != nil {
		return x.Consumed
	}
	return nil
}

type DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImplId        string                 `protobuf:"bytes,1,opt,name=impl_id,json=implId,proto3" json:"impl_id,omitempty"`
	InstanceData  []byte                 `protobuf:"bytes,2,opt,name=instance_data,json=instanceData,proto3" json:"instance_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_proto_systemtest_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{22}
}

func (x *DestroyRequest) GetImplId() string {
	if x != nil {
		return x.ImplId
	}
	return ""
}

func (x *DestroyRequest) GetInstanceData() []byte {
	if x != nil {
		return x.InstanceData
	}
	return nil
}

type DestroyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	mi := &file_proto_systemtest_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{23}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImplId        string                 `protobuf:"bytes,1,opt,name=impl_id,json=implId,proto3" json:"impl_id,omitempty"`
	InstanceData  []byte                 `protobuf:"bytes,2,opt,name=instance_data,json=instanceData,proto3" json:"instance_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_systemtest_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{24}
}

func (x *HealthCheckRequest) GetImplId() string {
	if x != nil {
		return x.ImplId
	}
	return ""
}

func (x *HealthCheckRequest) GetInstanceData() []byte {
	if x != nil {
		return x.InstanceData
	}
	return nil
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_systemtest_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{25}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Value_SchemaBlob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Contents      []byte                 `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value_SchemaBlob) Reset() {
	*x = Value_SchemaBlob{}
	mi := &file_proto_systemtest_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value_SchemaBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_SchemaBlob) ProtoMessage() {}

func (x *Value_SchemaBlob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systemtest_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_SchemaBlob.ProtoReflect.Descriptor instead.
func (*Value_SchemaBlob) Descriptor() ([]byte, []int) {
	return file_proto_systemtest_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Value_SchemaBlob) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *Value_SchemaBlob) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

var File_proto_systemtest_proto protoreflect.FileDescriptor

const file_proto_systemtest_proto_rawDesc = "" +
	"\n" +
	"\x16proto/systemtest.proto\x12\rsystemtest.v1\"\xe4\x01\n" +
	"\x05Value\x12\x12\n" +
	"\x03str\x18\x01 \x01(\tH\x00R\x03str\x12\x14\n" +
	"\x04data\x18\x03 \x01(\fH\x00R\x04data\x12B\n" +
	"\vschema_blob\x18\x04 \x01(\v2\x1f.systemtest.v1.Value.SchemaBlobH\x00R\n" +
	"schemaBlob\x12\x1d\n" +
	"\tint_value\x18\x05 \x01(\x05H\x00R\bintValue\x1aE\n" +
	"\n" +
	"SchemaBlob\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12\x1a\n" +
	"\bcontents\x18\x02 \x01(\fR\bcontentsB\a\n" +
	"\x05value\"\a\n" +
	"\x05Empty\"\x94\x02\n" +
	"\aSharing\x12:\n" +
	"\funrestricted\x18\x01 \x01(\v2\x14.systemtest.v1.EmptyH\x00R\funrestricted\x12C\n" +
	"\x11client_restricted\x18\x02 \x01(\v2\x14.systemtest.v1.EmptyH\x00R\x10clientRestricted\x125\n" +
	"\n" +
	"single_use\x18\x03 \x01(\v2\x14.systemtest.v1.EmptyH\x00R\tsingleUse\x12D\n" +
	"\x1emaximum_concurrent_connections\x18\x04 \x01(\x03R\x1cmaximumConcurrentConnectionsB\v\n" +
	"\tuse_scope\"\xdb\x03\n" +
	"\x12FixtureDescription\x12\x17\n" +
	"\aimpl_id\x18\x01 \x01(\tR\x06implId\x12!\n" +
	"\vbinary_path\x18\x02 \x01(\tH\x00R\n" +
	"binaryPath\x12%\n" +
	"\rcontainer_ref\x18\x03 \x01(\tH\x00R\fcontainerRef\x12E\n" +
	"\x06inputs\x18\x04 \x03(\v2-.systemtest.v1.FixtureDescription.InputsEntryR\x06inputs\x12!\n" +
	"\fimage_inputs\x18\x05 \x03(\tR\vimageInputs\x12\x1f\n" +
	"\vfile_inputs\x18\x06 \x03(\tR\n" +
	"fileInputs\x120\n" +
	"\asharing\x18\a \x01(\v2\x16.systemtest.v1.SharingR\asharing\x126\n" +
	"\x17startup_timeout_seconds\x18\b \x01(\x03R\x15startupTimeoutSeconds\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x1aO\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.systemtest.v1.ValueR\x05value:\x028\x01B\b\n" +
	"\x06plugin\"\xd9\x01\n" +
	"\x10TakeLeaseRequest\x12;\n" +
	"\afixture\x18\x01 \x01(\v2!.systemtest.v1.FixtureDescriptionR\afixture\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x03R\n" +
	"ttlSeconds\x124\n" +
	"\x16associated_tests_count\x18\x05 \x01(\rR\x14associatedTestsCount\"\x99\x02\n" +
	"\x11TakeLeaseResponse\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.systemtest.v1.LeaseStatusR\x06status\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12G\n" +
	"\aoutputs\x18\x03 \x03(\v2-.systemtest.v1.TakeLeaseResponse.OutputsEntryR\aoutputs\x12\x1a\n" +
	"\bmessages\x18\x04 \x03(\tR\bmessages\x1aP\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.systemtest.v1.ValueR\x05value:\x028\x01\"-\n" +
	"\x10KeepaliveRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"\x13\n" +
	"\x11KeepaliveResponse\"+\n" +
	"\x0eReleaseRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"\x11\n" +
	"\x0fReleaseResponse\"*\n" +
	"\rStatusRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"\xf8\x01\n" +
	"\x0eStatusResponse\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.systemtest.v1.LeaseStatusR\x06status\x12D\n" +
	"\aoutputs\x18\x02 \x03(\v2*.systemtest.v1.StatusResponse.OutputsEntryR\aoutputs\x12\x1a\n" +
	"\bmessages\x18\x03 \x03(\tR\bmessages\x1aP\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.systemtest.v1.ValueR\x05value:\x028\x01\"R\n" +
	"\x11DescribeResponses\x12=\n" +
	"\tresponses\x18\x01 \x03(\v2\x1f.systemtest.v1.DescribeResponseR\tresponses\"\xc9\x01\n" +
	"\x10DescribeResponse\x12\x17\n" +
	"\aimpl_id\x18\x01 \x01(\tR\x06implId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12F\n" +
	"\aschemas\x18\x03 \x03(\v2,.systemtest.v1.DescribeResponse.SchemasEntryR\aschemas\x1a:\n" +
	"\fSchemasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x01\n" +
	"\x10CreationMetadata\x12\x1d\n" +
	"\n" +
	"fixture_id\x18\x01 \x01(\tR\tfixtureId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12C\n" +
	"\x06labels\x18\x04 \x03(\v2+.systemtest.v1.CreationMetadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf8\x01\n" +
	"\rCreateRequest\x12\x17\n" +
	"\aimpl_id\x18\x01 \x01(\tR\x06implId\x12@\n" +
	"\x06inputs\x18\x02 \x03(\v2(.systemtest.v1.CreateRequest.InputsEntryR\x06inputs\x12;\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1f.systemtest.v1.CreationMetadataR\bmetadata\x1aO\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.systemtest.v1.ValueR\x05value:\x028\x01\"T\n" +
	"\x0eResourceAmount\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"d\n" +
	"\fResourcePool\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12;\n" +
	"\tresources\x18\x02 \x03(\v2\x1d.systemtest.v1.ResourceAmountR\tresources\"K\n" +
	"\x10ResourceRequests\x127\n" +
	"\bconsumes\x18\x01 \x03(\v2\x1b.systemtest.v1.ResourcePoolR\bconsumes\"\x96\x01\n" +
	"\x18FixtureElementStatusInfo\x12!\n" +
	"\felement_name\x18\x01 \x01(\tR\velementName\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.systemtest.v1.FixtureElementStatusR\x06status\x12\x1a\n" +
	"\bmessages\x18\x03 \x03(\tR\bmessages\"\xe1\x01\n" +
	"\x0eCreateProgress\x12;\n" +
	"\x06status\x18\x01 \x01(\x0e2#.systemtest.v1.CreateProgressStatusR\x06status\x12L\n" +
	"\relement_infos\x18\x02 \x03(\v2'.systemtest.v1.FixtureElementStatusInfoR\felementInfos\x129\n" +
	"\x06result\x18\x03 \x01(\v2\x1c.systemtest.v1.FixtureResultH\x00R\x06result\x88\x01\x01B\t\n" +
	"\a_result\"\xb6\x02\n" +
	"\rFixtureResult\x12C\n" +
	"\aoutputs\x18\x01 \x03(\v2).systemtest.v1.FixtureResult.OutputsEntryR\aoutputs\x120\n" +
	"\x14idle_timeout_seconds\x18\x02 \x01(\x03R\x12idleTimeoutSeconds\x12#\n" +
	"\rinstance_data\x18\x03 \x01(\fR\finstanceData\x127\n" +
	"\bconsumed\x18\x04 \x03(\v2\x1b.systemtest.v1.ResourcePoolR\bconsumed\x1aP\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.systemtest.v1.ValueR\x05value:\x028\x01\"N\n" +
	"\x0eDestroyRequest\x12\x17\n" +
	"\aimpl_id\x18\x01 \x01(\tR\x06implId\x12#\n" +
	"\rinstance_data\x18\x02 \x01(\fR\finstanceData\"\x11\n" +
	"\x0fDestroyResponse\"R\n" +
	"\x12HealthCheckRequest\x12\x17\n" +
	"\aimpl_id\x18\x01 \x01(\tR\x06implId\x12#\n" +
	"\rinstance_data\x18\x02 \x01(\fR\finstanceData\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*O\n" +
	"\vLeaseStatus\x12\x18\n" +
	"\x14LEASE_STATUS_UNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\r\n" +
	"\tSUCCEEDED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03*\xc6\x01\n" +
	"\x14CreateProgressStatus\x12\x1b\n" +
	"\x17CREATE_PROGRESS_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18CREATE_PROGRESS_ENQUEUED\x10\x01\x12\x1c\n" +
	"\x18CREATE_PROGRESS_CREATING\x10\x02\x12\x1b\n" +
	"\x17CREATE_PROGRESS_RUNNING\x10\x03\x12\x1d\n" +
	"\x19CREATE_PROGRESS_SUCCEEDED\x10\x04\x12\x19\n" +
	"\x15CREATE_PROGRESS_ERROR\x10\x05*\x89\x01\n" +
	"\x14FixtureElementStatus\x12\x1b\n" +
	"\x17FIXTURE_ELEMENT_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18FIXTURE_ELEMENT_CREATING\x10\x01\x12\x1b\n" +
	"\x17FIXTURE_ELEMENT_RUNNING\x10\x02\x12\x19\n" +
	"\x15FIXTURE_ELEMENT_ERROR\x10\x032\xca\x02\n" +
	"\x12CoordinatorService\x12N\n" +
	"\tTakeLease\x12\x1f.systemtest.v1.TakeLeaseRequest\x1a .systemtest.v1.TakeLeaseResponse\x12N\n" +
	"\tKeepalive\x12\x1f.systemtest.v1.KeepaliveRequest\x1a .systemtest.v1.KeepaliveResponse\x12M\n" +
	"\fReleaseLease\x12\x1d.systemtest.v1.ReleaseRequest\x1a\x1e.systemtest.v1.ReleaseResponse\x12E\n" +
	"\x06Status\x12\x1c.systemtest.v1.StatusRequest\x1a\x1d.systemtest.v1.StatusResponse2\xf8\x03\n" +
	"\x11CoordinatorPlugin\x12H\n" +
	"\x0eDescribePlugin\x12\x14.systemtest.v1.Empty\x1a .systemtest.v1.DescribeResponses\x12L\n" +
	"\x0fGetResourcePool\x12\x1c.systemtest.v1.CreateRequest\x1a\x1b.systemtest.v1.ResourcePool\x12T\n" +
	"\x13GetResourceRequests\x12\x1c.systemtest.v1.CreateRequest\x1a\x1f.systemtest.v1.ResourceRequests\x12N\n" +
	"\rCreateFixture\x12\x1c.systemtest.v1.CreateRequest\x1a\x1d.systemtest.v1.CreateProgress0\x01\x12O\n" +
	"\x0eDestroyFixture\x12\x1d.systemtest.v1.DestroyRequest\x1a\x1e.systemtest.v1.DestroyResponse\x12T\n" +
	"\vHealthCheck\x12!.systemtest.v1.HealthCheckRequest\x1a\".systemtest.v1.HealthCheckResponseBBZ@github.com/hermeticbuild/rules_systemtest/src/proto/systemtestpbb\x06proto3"

var (
	file_proto_systemtest_proto_rawDescOnce sync.Once
	file_proto_systemtest_proto_rawDescData []byte
)

func file_proto_systemtest_proto_rawDescGZIP() []byte {
	file_proto_systemtest_proto_rawDescOnce.Do(func() {
		file_proto_systemtest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_systemtest_proto_rawDesc), len(file_proto_systemtest_proto_rawDesc)))
	})
	return file_proto_systemtest_proto_rawDescData
}

var file_proto_systemtest_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_systemtest_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_proto_systemtest_proto_goTypes = []any{
	(LeaseStatus)(0),                 // 0: systemtest.v1.LeaseStatus
	(CreateProgressStatus)(0),        // 1: systemtest.v1.CreateProgressStatus
	(FixtureElementStatus)(0),        // 2: systemtest.v1.FixtureElementStatus
	(*Value)(nil),                    // 3: systemtest.v1.Value
	(*Empty)(nil),                    // 4: systemtest.v1.Empty
	(*Sharing)(nil),                  // 5: systemtest.v1.Sharing
	(*FixtureDescription)(nil),       // 6: systemtest.v1.FixtureDescription
	(*TakeLeaseRequest)(nil),         // 7: systemtest.v1.TakeLeaseRequest
	(*TakeLeaseResponse)(nil),        // 8: systemtest.v1.TakeLeaseResponse
	(*KeepaliveRequest)(nil),         // 9: systemtest.v1.KeepaliveRequest
	(*KeepaliveResponse)(nil),        // 10: systemtest.v1.KeepaliveResponse
	(*ReleaseRequest)(nil),           // 11: systemtest.v1.ReleaseRequest
	(*ReleaseResponse)(nil),          // 12: systemtest.v1.ReleaseResponse
	(*StatusRequest)(nil),            // 13: systemtest.v1.StatusRequest
	(*StatusResponse)(nil),           // 14: systemtest.v1.StatusResponse
	(*DescribeResponses)(nil),        // 15: systemtest.v1.DescribeResponses
	(*DescribeResponse)(nil),         // 16: systemtest.v1.DescribeResponse
	(*CreationMetadata)(nil),         // 17: systemtest.v1.CreationMetadata
	(*CreateRequest)(nil),            // 18: systemtest.v1.CreateRequest
	(*ResourceAmount)(nil),           // 19: systemtest.v1.ResourceAmount
	(*ResourcePool)(nil),             // 20: systemtest.v1.ResourcePool
	(*ResourceRequests)(nil),         // 21: systemtest.v1.ResourceRequests
	(*FixtureElementStatusInfo)(nil), // 22: systemtest.v1.FixtureElementStatusInfo
	(*CreateProgress)(nil),           // 23: systemtest.v1.CreateProgress
	(*FixtureResult)(nil),            // 24: systemtest.v1.FixtureResult
	(*DestroyRequest)(nil),           // 25: systemtest.v1.DestroyRequest
	(*DestroyResponse)(nil),          // 26: systemtest.v1.DestroyResponse
	(*HealthCheckRequest)(nil),       // 27: systemtest.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),      // 28: systemtest.v1.HealthCheckResponse
	(*Value_SchemaBlob)(nil),         // 29: systemtest.v1.Value.SchemaBlob
	nil,                              // 30: systemtest.v1.FixtureDescription.InputsEntry
	nil,                              // 31: systemtest.v1.TakeLeaseResponse.OutputsEntry
	nil,                              // 32: systemtest.v1.StatusResponse.OutputsEntry
	nil,                              // 33: systemtest.v1.DescribeResponse.SchemasEntry
	nil,                              // 34: systemtest.v1.CreationMetadata.LabelsEntry
	nil,                              // 35: systemtest.v1.CreateRequest.InputsEntry
	nil,                              // 36: systemtest.v1.FixtureResult.OutputsEntry
}
var file_proto_systemtest_proto_depIdxs = []int32{
	29, // 0: systemtest.v1.Value.schema_blob:type_name -> systemtest.v1.Value.SchemaBlob
	4,  // 1: systemtest.v1.Sharing.unrestricted:type_name -> systemtest.v1.Empty
	4,  // 2: systemtest.v1.Sharing.client_restricted:type_name -> systemtest.v1.Empty
	4,  // 3: systemtest.v1.Sharing.single_use:type_name -> systemtest.v1.Empty
	30, // 4: systemtest.v1.FixtureDescription.inputs:type_name -> systemtest.v1.FixtureDescription.InputsEntry
	5,  // 5: systemtest.v1.FixtureDescription.sharing:type_name -> systemtest.v1.Sharing
	6,  // 6: systemtest.v1.TakeLeaseRequest.fixture:type_name -> systemtest.v1.FixtureDescription
	0,  // 7: systemtest.v1.TakeLeaseResponse.status:type_name -> systemtest.v1.LeaseStatus
	31, // 8: systemtest.v1.TakeLeaseResponse.outputs:type_name -> systemtest.v1.TakeLeaseResponse.OutputsEntry
	0,  // 9: systemtest.v1.StatusResponse.status:type_name -> systemtest.v1.LeaseStatus
	32, // 10: systemtest.v1.StatusResponse.outputs:type_name -> systemtest.v1.StatusResponse.OutputsEntry
	16, // 11: systemtest.v1.DescribeResponses.responses:type_name -> systemtest.v1.DescribeResponse
	33, // 12: systemtest.v1.DescribeResponse.schemas:type_name -> systemtest.v1.DescribeResponse.SchemasEntry
	34, // 13: systemtest.v1.CreationMetadata.labels:type_name -> systemtest.v1.CreationMetadata.LabelsEntry
	35, // 14: systemtest.v1.CreateRequest.inputs:type_name -> systemtest.v1.CreateRequest.InputsEntry
	17, // 15: systemtest.v1.CreateRequest.metadata:type_name -> systemtest.v1.CreationMetadata
	19, // 16: systemtest.v1.ResourcePool.resources:type_name -> systemtest.v1.ResourceAmount
	20, // 17: systemtest.v1.ResourceRequests.consumes:type_name -> systemtest.v1.ResourcePool
	2,  // 18: systemtest.v1.FixtureElementStatusInfo.status:type_name -> systemtest.v1.FixtureElementStatus
	1,  // 19: systemtest.v1.CreateProgress.status:type_name -> systemtest.v1.CreateProgressStatus
	22, // 20: systemtest.v1.CreateProgress.element_infos:type_name -> systemtest.v1.FixtureElementStatusInfo
	24, // 21: systemtest.v1.CreateProgress.result:type_name -> systemtest.v1.FixtureResult
	36, // 22: systemtest.v1.FixtureResult.outputs:type_name -> systemtest.v1.FixtureResult.OutputsEntry
	20, // 23: systemtest.v1.FixtureResult.consumed:type_name -> systemtest.v1.ResourcePool
	3,  // 24: systemtest.v1.FixtureDescription.InputsEntry.value:type_name -> systemtest.v1.Value
	3,  // 25: systemtest.v1.TakeLeaseResponse.OutputsEntry.value:type_name -> systemtest.v1.Value
	3,  // 26: systemtest.v1.StatusResponse.OutputsEntry.value:type_name -> systemtest.v1.Value
	3,  // 27: systemtest.v1.CreateRequest.InputsEntry.value:type_name -> systemtest.v1.Value
	3,  // 28: systemtest.v1.FixtureResult.OutputsEntry.value:type_name -> systemtest.v1.Value
	7,  // 29: systemtest.v1.CoordinatorService.TakeLease:input_type -> systemtest.v1.TakeLeaseRequest
	9,  // 30: systemtest.v1.CoordinatorService.Keepalive:input_type -> systemtest.v1.KeepaliveRequest
	11, // 31: systemtest.v1.CoordinatorService.ReleaseLease:input_type -> systemtest.v1.ReleaseRequest
	13, // 32: systemtest.v1.CoordinatorService.Status:input_type -> systemtest.v1.StatusRequest
	4,  // 33: systemtest.v1.CoordinatorPlugin.DescribePlugin:input_type -> systemtest.v1.Empty
	18, // 34: systemtest.v1.CoordinatorPlugin.GetResourcePool:input_type -> systemtest.v1.CreateRequest
	18, // 35: systemtest.v1.CoordinatorPlugin.GetResourceRequests:input_type -> systemtest.v1.CreateRequest
	18, // 36: systemtest.v1.CoordinatorPlugin.CreateFixture:input_type -> systemtest.v1.CreateRequest
	25, // 37: systemtest.v1.CoordinatorPlugin.DestroyFixture:input_type -> systemtest.v1.DestroyRequest
	27, // 38: systemtest.v1.CoordinatorPlugin.HealthCheck:input_type -> systemtest.v1.HealthCheckRequest
	8,  // 39: systemtest.v1.CoordinatorService.TakeLease:output_type -> systemtest.v1.TakeLeaseResponse
	10, // 40: systemtest.v1.CoordinatorService.Keepalive:output_type -> systemtest.v1.KeepaliveResponse
	12, // 41: systemtest.v1.CoordinatorService.ReleaseLease:output_type -> systemtest.v1.ReleaseResponse
	14, // 42: systemtest.v1.CoordinatorService.Status:output_type -> systemtest.v1.StatusResponse
	15, // 43: systemtest.v1.CoordinatorPlugin.DescribePlugin:output_type -> systemtest.v1.DescribeResponses
	20, // 44: systemtest.v1.CoordinatorPlugin.GetResourcePool:output_type -> systemtest.v1.ResourcePool
	21, // 45: systemtest.v1.CoordinatorPlugin.GetResourceRequests:output_type -> systemtest.v1.ResourceRequests
	23, // 46: systemtest.v1.CoordinatorPlugin.CreateFixture:output_type -> systemtest.v1.CreateProgress
	26, // 47: systemtest.v1.CoordinatorPlugin.DestroyFixture:output_type -> systemtest.v1.DestroyResponse
	28, // 48: systemtest.v1.CoordinatorPlugin.HealthCheck:output_type -> systemtest.v1.HealthCheckResponse
	39, // [39:49] is the sub-list for method output_type
	29, // [29:39] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_proto_systemtest_proto_init() }
func file_proto_systemtest_proto_init() {
	if File_proto_systemtest_proto != nil {
		return
	}
	file_proto_systemtest_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_Str)(nil),
		(*Value_Data)(nil),
		(*Value_SchemaBlob_)(nil),
		(*Value_IntValue)(nil),
	}
	file_proto_systemtest_proto_msgTypes[2].OneofWrappers = []any{
		(*Sharing_Unrestricted)(nil),
		(*Sharing_ClientRestricted)(nil),
		(*Sharing_SingleUse)(nil),
	}
	file_proto_systemtest_proto_msgTypes[3].OneofWrappers = []any{
		(*FixtureDescription_BinaryPath)(nil),
		(*FixtureDescription_ContainerRef)(nil),
	}
	file_proto_systemtest_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_systemtest_proto_rawDesc), len(file_proto_systemtest_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_systemtest_proto_goTypes,
		DependencyIndexes: file_proto_systemtest_proto_depIdxs,
		EnumInfos:         file_proto_systemtest_proto_enumTypes,
		MessageInfos:      file_proto_systemtest_proto_msgTypes,
	}.Build()
	File_proto_systemtest_proto = out.File
	file_proto_systemtest_proto_goTypes = nil
	file_proto_systemtest_proto_depIdxs = nil
}
