// @generated

pub mod systemtest {
    pub mod v1 {
        // @generated
        // This file is @generated by prost-build.
        /// A single value on the wire.
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Value {
            #[prost(oneof = "value::Value", tags = "1, 3, 4, 5")]
            pub value: ::core::option::Option<value::Value>,
        }
        /// Nested message and enum types in `Value`.
        pub mod value {
            /// JSON conforming to schema_id, tagged with the id of a schema the emitting
            /// plugin advertises.
            #[derive(Clone, PartialEq, ::prost::Message)]
            pub struct SchemaBlob {
                #[prost(string, tag = "1")]
                pub schema_id: ::prost::alloc::string::String,
                #[prost(bytes = "vec", tag = "2")]
                pub contents: ::prost::alloc::vec::Vec<u8>,
            }
            #[derive(Clone, PartialEq, ::prost::Oneof)]
            pub enum Value {
                /// scalar; also JSON-encoded lists/dicts on inputs
                #[prost(string, tag = "1")]
                Str(::prost::alloc::string::String),
                /// raw bytes (e.g. inlined file contents)
                #[prost(bytes, tag = "3")]
                Data(::prost::alloc::vec::Vec<u8>),
                #[prost(message, tag = "4")]
                SchemaBlob(SchemaBlob),
                /// integer scalar (protojson: a JSON number)
                #[prost(int32, tag = "5")]
                IntValue(i32),
            }
        }
        #[derive(Clone, Copy, PartialEq, ::prost::Message)]
        pub struct Empty {}
        /// Reuse/sharing policy for a fixture. See design "Reuse, sharing, and slots".
        #[derive(Clone, Copy, PartialEq, ::prost::Message)]
        pub struct Sharing {
            /// "slots"
            #[prost(int64, tag = "4")]
            pub maximum_concurrent_connections: i64,
            #[prost(oneof = "sharing::UseScope", tags = "1, 2, 3")]
            pub use_scope: ::core::option::Option<sharing::UseScope>,
        }
        /// Nested message and enum types in `Sharing`.
        pub mod sharing {
            #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
            pub enum UseScope {
                /// any client_id may reuse
                #[prost(message, tag = "1")]
                Unrestricted(super::Empty),
                /// only the creating client_id (default)
                #[prost(message, tag = "2")]
                ClientRestricted(super::Empty),
                /// never reused
                #[prost(message, tag = "3")]
                SingleUse(super::Empty),
            }
        }
        /// The content-addressed recipe for a fixture.
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct FixtureDescription {
            #[prost(string, tag = "1")]
            pub impl_id: ::prost::alloc::string::String,
            #[prost(btree_map = "string, message", tag = "4")]
            pub inputs:
                ::prost::alloc::collections::BTreeMap<::prost::alloc::string::String, Value>,
            /// scaffold: unused
            #[prost(string, repeated, tag = "5")]
            pub image_inputs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
            /// scaffold: unused
            #[prost(string, repeated, tag = "6")]
            pub file_inputs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
            #[prost(message, optional, tag = "7")]
            pub sharing: ::core::option::Option<Sharing>,
            #[prost(int64, tag = "8")]
            pub startup_timeout_seconds: i64,
            /// human-readable; not part of identity
            #[prost(string, tag = "9")]
            pub name: ::prost::alloc::string::String,
            #[prost(oneof = "fixture_description::Plugin", tags = "2, 3")]
            pub plugin: ::core::option::Option<fixture_description::Plugin>,
        }
        /// Nested message and enum types in `FixtureDescription`.
        pub mod fixture_description {
            #[derive(Clone, PartialEq, ::prost::Oneof)]
            pub enum Plugin {
                /// local mode: runfiles path the coordinator starts
                #[prost(string, tag = "2")]
                BinaryPath(::prost::alloc::string::String),
                /// remote mode: digest-pinned (unused in scaffold)
                #[prost(string, tag = "3")]
                ContainerRef(::prost::alloc::string::String),
            }
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct TakeLeaseRequest {
            /// fully resolved
            #[prost(message, optional, tag = "1")]
            pub fixture: ::core::option::Option<FixtureDescription>,
            /// reuse key
            #[prost(string, tag = "2")]
            pub client_id: ::prost::alloc::string::String,
            /// accounting only
            #[prost(string, tag = "3")]
            pub owner: ::prost::alloc::string::String,
            #[prost(int64, tag = "4")]
            pub ttl_seconds: i64,
            #[prost(uint32, tag = "5")]
            pub associated_tests_count: u32,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct TakeLeaseResponse {
            #[prost(enumeration = "LeaseStatus", tag = "1")]
            pub status: i32,
            #[prost(string, tag = "2")]
            pub lease_id: ::prost::alloc::string::String,
            /// only on SUCCEEDED; forwarded verbatim
            #[prost(btree_map = "string, message", tag = "3")]
            pub outputs:
                ::prost::alloc::collections::BTreeMap<::prost::alloc::string::String, Value>,
            #[prost(string, repeated, tag = "4")]
            pub messages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct KeepaliveRequest {
            #[prost(string, tag = "1")]
            pub lease_id: ::prost::alloc::string::String,
        }
        #[derive(Clone, Copy, PartialEq, ::prost::Message)]
        pub struct KeepaliveResponse {}
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct ReleaseRequest {
            #[prost(string, tag = "1")]
            pub lease_id: ::prost::alloc::string::String,
        }
        #[derive(Clone, Copy, PartialEq, ::prost::Message)]
        pub struct ReleaseResponse {}
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct StatusRequest {
            #[prost(string, tag = "1")]
            pub lease_id: ::prost::alloc::string::String,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct StatusResponse {
            #[prost(enumeration = "LeaseStatus", tag = "1")]
            pub status: i32,
            #[prost(btree_map = "string, message", tag = "2")]
            pub outputs:
                ::prost::alloc::collections::BTreeMap<::prost::alloc::string::String, Value>,
            #[prost(string, repeated, tag = "3")]
            pub messages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct DescribeResponses {
            #[prost(message, repeated, tag = "1")]
            pub responses: ::prost::alloc::vec::Vec<DescribeResponse>,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct DescribeResponse {
            #[prost(string, tag = "1")]
            pub impl_id: ::prost::alloc::string::String,
            #[prost(string, tag = "2")]
            pub version: ::prost::alloc::string::String,
            /// schema_id -> JSON Schema text
            #[prost(btree_map = "string, string", tag = "3")]
            pub schemas: ::prost::alloc::collections::BTreeMap<
                ::prost::alloc::string::String,
                ::prost::alloc::string::String,
            >,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct CreationMetadata {
            /// stable id; key idempotency on this
            #[prost(string, tag = "1")]
            pub fixture_id: ::prost::alloc::string::String,
            #[prost(string, tag = "2")]
            pub client_id: ::prost::alloc::string::String,
            #[prost(string, tag = "3")]
            pub owner: ::prost::alloc::string::String,
            #[prost(btree_map = "string, string", tag = "4")]
            pub labels: ::prost::alloc::collections::BTreeMap<
                ::prost::alloc::string::String,
                ::prost::alloc::string::String,
            >,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct CreateRequest {
            #[prost(string, tag = "1")]
            pub impl_id: ::prost::alloc::string::String,
            /// file contents already inlined
            #[prost(btree_map = "string, message", tag = "2")]
            pub inputs:
                ::prost::alloc::collections::BTreeMap<::prost::alloc::string::String, Value>,
            #[prost(message, optional, tag = "3")]
            pub metadata: ::core::option::Option<CreationMetadata>,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct ResourceAmount {
            #[prost(string, tag = "1")]
            pub name: ::prost::alloc::string::String,
            #[prost(string, tag = "2")]
            pub unit: ::prost::alloc::string::String,
            #[prost(int64, tag = "3")]
            pub quantity: i64,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct ResourcePool {
            #[prost(string, tag = "1")]
            pub pool_id: ::prost::alloc::string::String,
            #[prost(message, repeated, tag = "2")]
            pub resources: ::prost::alloc::vec::Vec<ResourceAmount>,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct ResourceRequests {
            #[prost(message, repeated, tag = "1")]
            pub consumes: ::prost::alloc::vec::Vec<ResourcePool>,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct FixtureElementStatusInfo {
            #[prost(string, tag = "1")]
            pub element_name: ::prost::alloc::string::String,
            #[prost(enumeration = "FixtureElementStatus", tag = "2")]
            pub status: i32,
            #[prost(string, repeated, tag = "3")]
            pub messages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct CreateProgress {
            #[prost(enumeration = "CreateProgressStatus", tag = "1")]
            pub status: i32,
            #[prost(message, repeated, tag = "2")]
            pub element_infos: ::prost::alloc::vec::Vec<FixtureElementStatusInfo>,
            /// set once, on CREATE_PROGRESS_SUCCEEDED
            #[prost(message, optional, tag = "3")]
            pub result: ::core::option::Option<FixtureResult>,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct FixtureResult {
            #[prost(btree_map = "string, message", tag = "1")]
            pub outputs:
                ::prost::alloc::collections::BTreeMap<::prost::alloc::string::String, Value>,
            #[prost(int64, tag = "2")]
            pub idle_timeout_seconds: i64,
            /// opaque; handed back to Destroy/HealthCheck
            #[prost(bytes = "vec", tag = "3")]
            pub instance_data: ::prost::alloc::vec::Vec<u8>,
            #[prost(message, repeated, tag = "4")]
            pub consumed: ::prost::alloc::vec::Vec<ResourcePool>,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct DestroyRequest {
            #[prost(string, tag = "1")]
            pub impl_id: ::prost::alloc::string::String,
            #[prost(bytes = "vec", tag = "2")]
            pub instance_data: ::prost::alloc::vec::Vec<u8>,
        }
        #[derive(Clone, Copy, PartialEq, ::prost::Message)]
        pub struct DestroyResponse {}
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct HealthCheckRequest {
            #[prost(string, tag = "1")]
            pub impl_id: ::prost::alloc::string::String,
            #[prost(bytes = "vec", tag = "2")]
            pub instance_data: ::prost::alloc::vec::Vec<u8>,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct HealthCheckResponse {
            #[prost(bool, tag = "1")]
            pub healthy: bool,
            #[prost(string, tag = "2")]
            pub message: ::prost::alloc::string::String,
        }
        #[derive(
            Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration,
        )]
        #[repr(i32)]
        pub enum LeaseStatus {
            Unknown = 0,
            Pending = 1,
            Succeeded = 2,
            Failed = 3,
        }
        impl LeaseStatus {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Unknown => "LEASE_STATUS_UNKNOWN",
                    Self::Pending => "PENDING",
                    Self::Succeeded => "SUCCEEDED",
                    Self::Failed => "FAILED",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "LEASE_STATUS_UNKNOWN" => Some(Self::Unknown),
                    "PENDING" => Some(Self::Pending),
                    "SUCCEEDED" => Some(Self::Succeeded),
                    "FAILED" => Some(Self::Failed),
                    _ => None,
                }
            }
        }
        #[derive(
            Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration,
        )]
        #[repr(i32)]
        pub enum CreateProgressStatus {
            CreateProgressUnknown = 0,
            CreateProgressEnqueued = 1,
            CreateProgressCreating = 2,
            CreateProgressRunning = 3,
            /// terminal success; result is set
            CreateProgressSucceeded = 4,
            /// terminal failure
            CreateProgressError = 5,
        }
        impl CreateProgressStatus {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::CreateProgressUnknown => "CREATE_PROGRESS_UNKNOWN",
                    Self::CreateProgressEnqueued => "CREATE_PROGRESS_ENQUEUED",
                    Self::CreateProgressCreating => "CREATE_PROGRESS_CREATING",
                    Self::CreateProgressRunning => "CREATE_PROGRESS_RUNNING",
                    Self::CreateProgressSucceeded => "CREATE_PROGRESS_SUCCEEDED",
                    Self::CreateProgressError => "CREATE_PROGRESS_ERROR",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "CREATE_PROGRESS_UNKNOWN" => Some(Self::CreateProgressUnknown),
                    "CREATE_PROGRESS_ENQUEUED" => Some(Self::CreateProgressEnqueued),
                    "CREATE_PROGRESS_CREATING" => Some(Self::CreateProgressCreating),
                    "CREATE_PROGRESS_RUNNING" => Some(Self::CreateProgressRunning),
                    "CREATE_PROGRESS_SUCCEEDED" => Some(Self::CreateProgressSucceeded),
                    "CREATE_PROGRESS_ERROR" => Some(Self::CreateProgressError),
                    _ => None,
                }
            }
        }
        #[derive(
            Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration,
        )]
        #[repr(i32)]
        pub enum FixtureElementStatus {
            FixtureElementUnknown = 0,
            FixtureElementCreating = 1,
            FixtureElementRunning = 2,
            FixtureElementError = 3,
        }
        impl FixtureElementStatus {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::FixtureElementUnknown => "FIXTURE_ELEMENT_UNKNOWN",
                    Self::FixtureElementCreating => "FIXTURE_ELEMENT_CREATING",
                    Self::FixtureElementRunning => "FIXTURE_ELEMENT_RUNNING",
                    Self::FixtureElementError => "FIXTURE_ELEMENT_ERROR",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "FIXTURE_ELEMENT_UNKNOWN" => Some(Self::FixtureElementUnknown),
                    "FIXTURE_ELEMENT_CREATING" => Some(Self::FixtureElementCreating),
                    "FIXTURE_ELEMENT_RUNNING" => Some(Self::FixtureElementRunning),
                    "FIXTURE_ELEMENT_ERROR" => Some(Self::FixtureElementError),
                    _ => None,
                }
            }
        }
        // @@protoc_insertion_point(module)

        // @generated
        /// Generated client implementations.
        pub mod coordinator_service_client {
            #![allow(
                unused_variables,
                dead_code,
                missing_docs,
                clippy::wildcard_imports,
                clippy::let_unit_value
            )]
            use tonic::codegen::http::Uri;
            use tonic::codegen::*;
            #[derive(Debug, Clone)]
            pub struct CoordinatorServiceClient<T> {
                inner: tonic::client::Grpc<T>,
            }
            impl CoordinatorServiceClient<tonic::transport::Channel> {
                /// Attempt to create a new client by connecting to a given endpoint.
                pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
                where
                    D: TryInto<tonic::transport::Endpoint>,
                    D::Error: Into<StdError>,
                {
                    let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
                    Ok(Self::new(conn))
                }
            }
            impl<T> CoordinatorServiceClient<T>
            where
                T: tonic::client::GrpcService<tonic::body::BoxBody>,
                T::Error: Into<StdError>,
                T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
                <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
            {
                pub fn new(inner: T) -> Self {
                    let inner = tonic::client::Grpc::new(inner);
                    Self { inner }
                }
                pub fn with_origin(inner: T, origin: Uri) -> Self {
                    let inner = tonic::client::Grpc::with_origin(inner, origin);
                    Self { inner }
                }
                pub fn with_interceptor<F>(
                    inner: T,
                    interceptor: F,
                ) -> CoordinatorServiceClient<InterceptedService<T, F>>
                where
                    F: tonic::service::Interceptor,
                    T::ResponseBody: Default,
                    T: tonic::codegen::Service<
                        http::Request<tonic::body::BoxBody>,
                        Response = http::Response<
                            <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                        >,
                    >,
                    <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                        Into<StdError> + std::marker::Send + std::marker::Sync,
                {
                    CoordinatorServiceClient::new(InterceptedService::new(inner, interceptor))
                }
                /// Compress requests with the given encoding.
                ///
                /// This requires the server to support it otherwise it might respond with an
                /// error.
                #[must_use]
                pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
                    self.inner = self.inner.send_compressed(encoding);
                    self
                }
                /// Enable decompressing responses.
                #[must_use]
                pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
                    self.inner = self.inner.accept_compressed(encoding);
                    self
                }
                /// Limits the maximum size of a decoded message.
                ///
                /// Default: `4MB`
                #[must_use]
                pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
                    self.inner = self.inner.max_decoding_message_size(limit);
                    self
                }
                /// Limits the maximum size of an encoded message.
                ///
                /// Default: `usize::MAX`
                #[must_use]
                pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
                    self.inner = self.inner.max_encoding_message_size(limit);
                    self
                }
                pub async fn take_lease(
                    &mut self,
                    request: impl tonic::IntoRequest<super::TakeLeaseRequest>,
                ) -> std::result::Result<tonic::Response<super::TakeLeaseResponse>, tonic::Status>
                {
                    self.inner.ready().await.map_err(|e| {
                        tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
                    })?;
                    let codec = tonic::codec::ProstCodec::default();
                    let path = http::uri::PathAndQuery::from_static(
                        "/systemtest.v1.CoordinatorService/TakeLease",
                    );
                    let mut req = request.into_request();
                    req.extensions_mut().insert(GrpcMethod::new(
                        "systemtest.v1.CoordinatorService",
                        "TakeLease",
                    ));
                    self.inner.unary(req, path, codec).await
                }
                pub async fn keepalive(
                    &mut self,
                    request: impl tonic::IntoRequest<super::KeepaliveRequest>,
                ) -> std::result::Result<tonic::Response<super::KeepaliveResponse>, tonic::Status>
                {
                    self.inner.ready().await.map_err(|e| {
                        tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
                    })?;
                    let codec = tonic::codec::ProstCodec::default();
                    let path = http::uri::PathAndQuery::from_static(
                        "/systemtest.v1.CoordinatorService/Keepalive",
                    );
                    let mut req = request.into_request();
                    req.extensions_mut().insert(GrpcMethod::new(
                        "systemtest.v1.CoordinatorService",
                        "Keepalive",
                    ));
                    self.inner.unary(req, path, codec).await
                }
                pub async fn release_lease(
                    &mut self,
                    request: impl tonic::IntoRequest<super::ReleaseRequest>,
                ) -> std::result::Result<tonic::Response<super::ReleaseResponse>, tonic::Status>
                {
                    self.inner.ready().await.map_err(|e| {
                        tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
                    })?;
                    let codec = tonic::codec::ProstCodec::default();
                    let path = http::uri::PathAndQuery::from_static(
                        "/systemtest.v1.CoordinatorService/ReleaseLease",
                    );
                    let mut req = request.into_request();
                    req.extensions_mut().insert(GrpcMethod::new(
                        "systemtest.v1.CoordinatorService",
                        "ReleaseLease",
                    ));
                    self.inner.unary(req, path, codec).await
                }
                pub async fn status(
                    &mut self,
                    request: impl tonic::IntoRequest<super::StatusRequest>,
                ) -> std::result::Result<tonic::Response<super::StatusResponse>, tonic::Status>
                {
                    self.inner.ready().await.map_err(|e| {
                        tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
                    })?;
                    let codec = tonic::codec::ProstCodec::default();
                    let path = http::uri::PathAndQuery::from_static(
                        "/systemtest.v1.CoordinatorService/Status",
                    );
                    let mut req = request.into_request();
                    req.extensions_mut().insert(GrpcMethod::new(
                        "systemtest.v1.CoordinatorService",
                        "Status",
                    ));
                    self.inner.unary(req, path, codec).await
                }
            }
        }
        /// Generated server implementations.
        pub mod coordinator_service_server {
            #![allow(
                unused_variables,
                dead_code,
                missing_docs,
                clippy::wildcard_imports,
                clippy::let_unit_value
            )]
            use tonic::codegen::*;
            /// Generated trait containing gRPC methods that should be implemented for use with CoordinatorServiceServer.
            #[async_trait]
            pub trait CoordinatorService: std::marker::Send + std::marker::Sync + 'static {
                async fn take_lease(
                    &self,
                    request: tonic::Request<super::TakeLeaseRequest>,
                ) -> std::result::Result<tonic::Response<super::TakeLeaseResponse>, tonic::Status>;
                async fn keepalive(
                    &self,
                    request: tonic::Request<super::KeepaliveRequest>,
                ) -> std::result::Result<tonic::Response<super::KeepaliveResponse>, tonic::Status>;
                async fn release_lease(
                    &self,
                    request: tonic::Request<super::ReleaseRequest>,
                ) -> std::result::Result<tonic::Response<super::ReleaseResponse>, tonic::Status>;
                async fn status(
                    &self,
                    request: tonic::Request<super::StatusRequest>,
                ) -> std::result::Result<tonic::Response<super::StatusResponse>, tonic::Status>;
            }
            #[derive(Debug)]
            pub struct CoordinatorServiceServer<T> {
                inner: Arc<T>,
                accept_compression_encodings: EnabledCompressionEncodings,
                send_compression_encodings: EnabledCompressionEncodings,
                max_decoding_message_size: Option<usize>,
                max_encoding_message_size: Option<usize>,
            }
            impl<T> CoordinatorServiceServer<T> {
                pub fn new(inner: T) -> Self {
                    Self::from_arc(Arc::new(inner))
                }
                pub fn from_arc(inner: Arc<T>) -> Self {
                    Self {
                        inner,
                        accept_compression_encodings: Default::default(),
                        send_compression_encodings: Default::default(),
                        max_decoding_message_size: None,
                        max_encoding_message_size: None,
                    }
                }
                pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
                where
                    F: tonic::service::Interceptor,
                {
                    InterceptedService::new(Self::new(inner), interceptor)
                }
                /// Enable decompressing requests with the given encoding.
                #[must_use]
                pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
                    self.accept_compression_encodings.enable(encoding);
                    self
                }
                /// Compress responses with the given encoding, if the client supports it.
                #[must_use]
                pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
                    self.send_compression_encodings.enable(encoding);
                    self
                }
                /// Limits the maximum size of a decoded message.
                ///
                /// Default: `4MB`
                #[must_use]
                pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
                    self.max_decoding_message_size = Some(limit);
                    self
                }
                /// Limits the maximum size of an encoded message.
                ///
                /// Default: `usize::MAX`
                #[must_use]
                pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
                    self.max_encoding_message_size = Some(limit);
                    self
                }
            }
            impl<T, B> tonic::codegen::Service<http::Request<B>> for CoordinatorServiceServer<T>
            where
                T: CoordinatorService,
                B: Body + std::marker::Send + 'static,
                B::Error: Into<StdError> + std::marker::Send + 'static,
            {
                type Response = http::Response<tonic::body::BoxBody>;
                type Error = std::convert::Infallible;
                type Future = BoxFuture<Self::Response, Self::Error>;
                fn poll_ready(
                    &mut self,
                    _cx: &mut Context<'_>,
                ) -> Poll<std::result::Result<(), Self::Error>> {
                    Poll::Ready(Ok(()))
                }
                fn call(&mut self, req: http::Request<B>) -> Self::Future {
                    match req.uri().path() {
                        "/systemtest.v1.CoordinatorService/TakeLease" => {
                            #[allow(non_camel_case_types)]
                            struct TakeLeaseSvc<T: CoordinatorService>(pub Arc<T>);
                            impl<T: CoordinatorService>
                                tonic::server::UnaryService<super::TakeLeaseRequest>
                                for TakeLeaseSvc<T>
                            {
                                type Response = super::TakeLeaseResponse;
                                type Future =
                                    BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                                fn call(
                                    &mut self,
                                    request: tonic::Request<super::TakeLeaseRequest>,
                                ) -> Self::Future {
                                    let inner = Arc::clone(&self.0);
                                    let fut = async move {
                                        <T as CoordinatorService>::take_lease(&inner, request).await
                                    };
                                    Box::pin(fut)
                                }
                            }
                            let accept_compression_encodings = self.accept_compression_encodings;
                            let send_compression_encodings = self.send_compression_encodings;
                            let max_decoding_message_size = self.max_decoding_message_size;
                            let max_encoding_message_size = self.max_encoding_message_size;
                            let inner = self.inner.clone();
                            let fut = async move {
                                let method = TakeLeaseSvc(inner);
                                let codec = tonic::codec::ProstCodec::default();
                                let mut grpc = tonic::server::Grpc::new(codec)
                                    .apply_compression_config(
                                        accept_compression_encodings,
                                        send_compression_encodings,
                                    )
                                    .apply_max_message_size_config(
                                        max_decoding_message_size,
                                        max_encoding_message_size,
                                    );
                                let res = grpc.unary(method, req).await;
                                Ok(res)
                            };
                            Box::pin(fut)
                        }
                        "/systemtest.v1.CoordinatorService/Keepalive" => {
                            #[allow(non_camel_case_types)]
                            struct KeepaliveSvc<T: CoordinatorService>(pub Arc<T>);
                            impl<T: CoordinatorService>
                                tonic::server::UnaryService<super::KeepaliveRequest>
                                for KeepaliveSvc<T>
                            {
                                type Response = super::KeepaliveResponse;
                                type Future =
                                    BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                                fn call(
                                    &mut self,
                                    request: tonic::Request<super::KeepaliveRequest>,
                                ) -> Self::Future {
                                    let inner = Arc::clone(&self.0);
                                    let fut = async move {
                                        <T as CoordinatorService>::keepalive(&inner, request).await
                                    };
                                    Box::pin(fut)
                                }
                            }
                            let accept_compression_encodings = self.accept_compression_encodings;
                            let send_compression_encodings = self.send_compression_encodings;
                            let max_decoding_message_size = self.max_decoding_message_size;
                            let max_encoding_message_size = self.max_encoding_message_size;
                            let inner = self.inner.clone();
                            let fut = async move {
                                let method = KeepaliveSvc(inner);
                                let codec = tonic::codec::ProstCodec::default();
                                let mut grpc = tonic::server::Grpc::new(codec)
                                    .apply_compression_config(
                                        accept_compression_encodings,
                                        send_compression_encodings,
                                    )
                                    .apply_max_message_size_config(
                                        max_decoding_message_size,
                                        max_encoding_message_size,
                                    );
                                let res = grpc.unary(method, req).await;
                                Ok(res)
                            };
                            Box::pin(fut)
                        }
                        "/systemtest.v1.CoordinatorService/ReleaseLease" => {
                            #[allow(non_camel_case_types)]
                            struct ReleaseLeaseSvc<T: CoordinatorService>(pub Arc<T>);
                            impl<T: CoordinatorService>
                                tonic::server::UnaryService<super::ReleaseRequest>
                                for ReleaseLeaseSvc<T>
                            {
                                type Response = super::ReleaseResponse;
                                type Future =
                                    BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                                fn call(
                                    &mut self,
                                    request: tonic::Request<super::ReleaseRequest>,
                                ) -> Self::Future {
                                    let inner = Arc::clone(&self.0);
                                    let fut = async move {
                                        <T as CoordinatorService>::release_lease(&inner, request)
                                            .await
                                    };
                                    Box::pin(fut)
                                }
                            }
                            let accept_compression_encodings = self.accept_compression_encodings;
                            let send_compression_encodings = self.send_compression_encodings;
                            let max_decoding_message_size = self.max_decoding_message_size;
                            let max_encoding_message_size = self.max_encoding_message_size;
                            let inner = self.inner.clone();
                            let fut = async move {
                                let method = ReleaseLeaseSvc(inner);
                                let codec = tonic::codec::ProstCodec::default();
                                let mut grpc = tonic::server::Grpc::new(codec)
                                    .apply_compression_config(
                                        accept_compression_encodings,
                                        send_compression_encodings,
                                    )
                                    .apply_max_message_size_config(
                                        max_decoding_message_size,
                                        max_encoding_message_size,
                                    );
                                let res = grpc.unary(method, req).await;
                                Ok(res)
                            };
                            Box::pin(fut)
                        }
                        "/systemtest.v1.CoordinatorService/Status" => {
                            #[allow(non_camel_case_types)]
                            struct StatusSvc<T: CoordinatorService>(pub Arc<T>);
                            impl<T: CoordinatorService>
                                tonic::server::UnaryService<super::StatusRequest> for StatusSvc<T>
                            {
                                type Response = super::StatusResponse;
                                type Future =
                                    BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                                fn call(
                                    &mut self,
                                    request: tonic::Request<super::StatusRequest>,
                                ) -> Self::Future {
                                    let inner = Arc::clone(&self.0);
                                    let fut = async move {
                                        <T as CoordinatorService>::status(&inner, request).await
                                    };
                                    Box::pin(fut)
                                }
                            }
                            let accept_compression_encodings = self.accept_compression_encodings;
                            let send_compression_encodings = self.send_compression_encodings;
                            let max_decoding_message_size = self.max_decoding_message_size;
                            let max_encoding_message_size = self.max_encoding_message_size;
                            let inner = self.inner.clone();
                            let fut = async move {
                                let method = StatusSvc(inner);
                                let codec = tonic::codec::ProstCodec::default();
                                let mut grpc = tonic::server::Grpc::new(codec)
                                    .apply_compression_config(
                                        accept_compression_encodings,
                                        send_compression_encodings,
                                    )
                                    .apply_max_message_size_config(
                                        max_decoding_message_size,
                                        max_encoding_message_size,
                                    );
                                let res = grpc.unary(method, req).await;
                                Ok(res)
                            };
                            Box::pin(fut)
                        }
                        _ => Box::pin(async move {
                            let mut response = http::Response::new(empty_body());
                            let headers = response.headers_mut();
                            headers.insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                            headers.insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                            Ok(response)
                        }),
                    }
                }
            }
            impl<T> Clone for CoordinatorServiceServer<T> {
                fn clone(&self) -> Self {
                    let inner = self.inner.clone();
                    Self {
                        inner,
                        accept_compression_encodings: self.accept_compression_encodings,
                        send_compression_encodings: self.send_compression_encodings,
                        max_decoding_message_size: self.max_decoding_message_size,
                        max_encoding_message_size: self.max_encoding_message_size,
                    }
                }
            }
            /// Generated gRPC service name
            pub const SERVICE_NAME: &str = "systemtest.v1.CoordinatorService";
            impl<T> tonic::server::NamedService for CoordinatorServiceServer<T> {
                const NAME: &'static str = SERVICE_NAME;
            }
        }
        /// Generated client implementations.
        pub mod coordinator_plugin_client {
            #![allow(
                unused_variables,
                dead_code,
                missing_docs,
                clippy::wildcard_imports,
                clippy::let_unit_value
            )]
            use tonic::codegen::http::Uri;
            use tonic::codegen::*;
            ///
            #[derive(Debug, Clone)]
            pub struct CoordinatorPluginClient<T> {
                inner: tonic::client::Grpc<T>,
            }
            impl CoordinatorPluginClient<tonic::transport::Channel> {
                /// Attempt to create a new client by connecting to a given endpoint.
                pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
                where
                    D: TryInto<tonic::transport::Endpoint>,
                    D::Error: Into<StdError>,
                {
                    let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
                    Ok(Self::new(conn))
                }
            }
            impl<T> CoordinatorPluginClient<T>
            where
                T: tonic::client::GrpcService<tonic::body::BoxBody>,
                T::Error: Into<StdError>,
                T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
                <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
            {
                pub fn new(inner: T) -> Self {
                    let inner = tonic::client::Grpc::new(inner);
                    Self { inner }
                }
                pub fn with_origin(inner: T, origin: Uri) -> Self {
                    let inner = tonic::client::Grpc::with_origin(inner, origin);
                    Self { inner }
                }
                pub fn with_interceptor<F>(
                    inner: T,
                    interceptor: F,
                ) -> CoordinatorPluginClient<InterceptedService<T, F>>
                where
                    F: tonic::service::Interceptor,
                    T::ResponseBody: Default,
                    T: tonic::codegen::Service<
                        http::Request<tonic::body::BoxBody>,
                        Response = http::Response<
                            <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                        >,
                    >,
                    <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                        Into<StdError> + std::marker::Send + std::marker::Sync,
                {
                    CoordinatorPluginClient::new(InterceptedService::new(inner, interceptor))
                }
                /// Compress requests with the given encoding.
                ///
                /// This requires the server to support it otherwise it might respond with an
                /// error.
                #[must_use]
                pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
                    self.inner = self.inner.send_compressed(encoding);
                    self
                }
                /// Enable decompressing responses.
                #[must_use]
                pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
                    self.inner = self.inner.accept_compressed(encoding);
                    self
                }
                /// Limits the maximum size of a decoded message.
                ///
                /// Default: `4MB`
                #[must_use]
                pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
                    self.inner = self.inner.max_decoding_message_size(limit);
                    self
                }
                /// Limits the maximum size of an encoded message.
                ///
                /// Default: `usize::MAX`
                #[must_use]
                pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
                    self.inner = self.inner.max_encoding_message_size(limit);
                    self
                }
                ///
                pub async fn describe_plugin(
                    &mut self,
                    request: impl tonic::IntoRequest<super::Empty>,
                ) -> std::result::Result<tonic::Response<super::DescribeResponses>, tonic::Status>
                {
                    self.inner.ready().await.map_err(|e| {
                        tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
                    })?;
                    let codec = tonic::codec::ProstCodec::default();
                    let path = http::uri::PathAndQuery::from_static(
                        "/systemtest.v1.CoordinatorPlugin/DescribePlugin",
                    );
                    let mut req = request.into_request();
                    req.extensions_mut().insert(GrpcMethod::new(
                        "systemtest.v1.CoordinatorPlugin",
                        "DescribePlugin",
                    ));
                    self.inner.unary(req, path, codec).await
                }
                ///
                pub async fn get_resource_pool(
                    &mut self,
                    request: impl tonic::IntoRequest<super::CreateRequest>,
                ) -> std::result::Result<tonic::Response<super::ResourcePool>, tonic::Status>
                {
                    self.inner.ready().await.map_err(|e| {
                        tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
                    })?;
                    let codec = tonic::codec::ProstCodec::default();
                    let path = http::uri::PathAndQuery::from_static(
                        "/systemtest.v1.CoordinatorPlugin/GetResourcePool",
                    );
                    let mut req = request.into_request();
                    req.extensions_mut().insert(GrpcMethod::new(
                        "systemtest.v1.CoordinatorPlugin",
                        "GetResourcePool",
                    ));
                    self.inner.unary(req, path, codec).await
                }
                pub async fn get_resource_requests(
                    &mut self,
                    request: impl tonic::IntoRequest<super::CreateRequest>,
                ) -> std::result::Result<tonic::Response<super::ResourceRequests>, tonic::Status>
                {
                    self.inner.ready().await.map_err(|e| {
                        tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
                    })?;
                    let codec = tonic::codec::ProstCodec::default();
                    let path = http::uri::PathAndQuery::from_static(
                        "/systemtest.v1.CoordinatorPlugin/GetResourceRequests",
                    );
                    let mut req = request.into_request();
                    req.extensions_mut().insert(GrpcMethod::new(
                        "systemtest.v1.CoordinatorPlugin",
                        "GetResourceRequests",
                    ));
                    self.inner.unary(req, path, codec).await
                }
                pub async fn create_fixture(
                    &mut self,
                    request: impl tonic::IntoRequest<super::CreateRequest>,
                ) -> std::result::Result<
                    tonic::Response<tonic::codec::Streaming<super::CreateProgress>>,
                    tonic::Status,
                > {
                    self.inner.ready().await.map_err(|e| {
                        tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
                    })?;
                    let codec = tonic::codec::ProstCodec::default();
                    let path = http::uri::PathAndQuery::from_static(
                        "/systemtest.v1.CoordinatorPlugin/CreateFixture",
                    );
                    let mut req = request.into_request();
                    req.extensions_mut().insert(GrpcMethod::new(
                        "systemtest.v1.CoordinatorPlugin",
                        "CreateFixture",
                    ));
                    self.inner.server_streaming(req, path, codec).await
                }
                pub async fn destroy_fixture(
                    &mut self,
                    request: impl tonic::IntoRequest<super::DestroyRequest>,
                ) -> std::result::Result<tonic::Response<super::DestroyResponse>, tonic::Status>
                {
                    self.inner.ready().await.map_err(|e| {
                        tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
                    })?;
                    let codec = tonic::codec::ProstCodec::default();
                    let path = http::uri::PathAndQuery::from_static(
                        "/systemtest.v1.CoordinatorPlugin/DestroyFixture",
                    );
                    let mut req = request.into_request();
                    req.extensions_mut().insert(GrpcMethod::new(
                        "systemtest.v1.CoordinatorPlugin",
                        "DestroyFixture",
                    ));
                    self.inner.unary(req, path, codec).await
                }
                pub async fn health_check(
                    &mut self,
                    request: impl tonic::IntoRequest<super::HealthCheckRequest>,
                ) -> std::result::Result<tonic::Response<super::HealthCheckResponse>, tonic::Status>
                {
                    self.inner.ready().await.map_err(|e| {
                        tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
                    })?;
                    let codec = tonic::codec::ProstCodec::default();
                    let path = http::uri::PathAndQuery::from_static(
                        "/systemtest.v1.CoordinatorPlugin/HealthCheck",
                    );
                    let mut req = request.into_request();
                    req.extensions_mut().insert(GrpcMethod::new(
                        "systemtest.v1.CoordinatorPlugin",
                        "HealthCheck",
                    ));
                    self.inner.unary(req, path, codec).await
                }
            }
        }
        /// Generated server implementations.
        pub mod coordinator_plugin_server {
            #![allow(
                unused_variables,
                dead_code,
                missing_docs,
                clippy::wildcard_imports,
                clippy::let_unit_value
            )]
            use tonic::codegen::*;
            /// Generated trait containing gRPC methods that should be implemented for use with CoordinatorPluginServer.
            #[async_trait]
            pub trait CoordinatorPlugin: std::marker::Send + std::marker::Sync + 'static {
                ///
                async fn describe_plugin(
                    &self,
                    request: tonic::Request<super::Empty>,
                ) -> std::result::Result<tonic::Response<super::DescribeResponses>, tonic::Status>;
                ///
                async fn get_resource_pool(
                    &self,
                    request: tonic::Request<super::CreateRequest>,
                ) -> std::result::Result<tonic::Response<super::ResourcePool>, tonic::Status>;
                async fn get_resource_requests(
                    &self,
                    request: tonic::Request<super::CreateRequest>,
                ) -> std::result::Result<tonic::Response<super::ResourceRequests>, tonic::Status>;
                /// Server streaming response type for the CreateFixture method.
                type CreateFixtureStream: tonic::codegen::tokio_stream::Stream<
                        Item = std::result::Result<super::CreateProgress, tonic::Status>,
                    > + std::marker::Send
                    + 'static;
                async fn create_fixture(
                    &self,
                    request: tonic::Request<super::CreateRequest>,
                ) -> std::result::Result<tonic::Response<Self::CreateFixtureStream>, tonic::Status>;
                async fn destroy_fixture(
                    &self,
                    request: tonic::Request<super::DestroyRequest>,
                ) -> std::result::Result<tonic::Response<super::DestroyResponse>, tonic::Status>;
                async fn health_check(
                    &self,
                    request: tonic::Request<super::HealthCheckRequest>,
                ) -> std::result::Result<tonic::Response<super::HealthCheckResponse>, tonic::Status>;
            }
            ///
            #[derive(Debug)]
            pub struct CoordinatorPluginServer<T> {
                inner: Arc<T>,
                accept_compression_encodings: EnabledCompressionEncodings,
                send_compression_encodings: EnabledCompressionEncodings,
                max_decoding_message_size: Option<usize>,
                max_encoding_message_size: Option<usize>,
            }
            impl<T> CoordinatorPluginServer<T> {
                pub fn new(inner: T) -> Self {
                    Self::from_arc(Arc::new(inner))
                }
                pub fn from_arc(inner: Arc<T>) -> Self {
                    Self {
                        inner,
                        accept_compression_encodings: Default::default(),
                        send_compression_encodings: Default::default(),
                        max_decoding_message_size: None,
                        max_encoding_message_size: None,
                    }
                }
                pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
                where
                    F: tonic::service::Interceptor,
                {
                    InterceptedService::new(Self::new(inner), interceptor)
                }
                /// Enable decompressing requests with the given encoding.
                #[must_use]
                pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
                    self.accept_compression_encodings.enable(encoding);
                    self
                }
                /// Compress responses with the given encoding, if the client supports it.
                #[must_use]
                pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
                    self.send_compression_encodings.enable(encoding);
                    self
                }
                /// Limits the maximum size of a decoded message.
                ///
                /// Default: `4MB`
                #[must_use]
                pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
                    self.max_decoding_message_size = Some(limit);
                    self
                }
                /// Limits the maximum size of an encoded message.
                ///
                /// Default: `usize::MAX`
                #[must_use]
                pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
                    self.max_encoding_message_size = Some(limit);
                    self
                }
            }
            impl<T, B> tonic::codegen::Service<http::Request<B>> for CoordinatorPluginServer<T>
            where
                T: CoordinatorPlugin,
                B: Body + std::marker::Send + 'static,
                B::Error: Into<StdError> + std::marker::Send + 'static,
            {
                type Response = http::Response<tonic::body::BoxBody>;
                type Error = std::convert::Infallible;
                type Future = BoxFuture<Self::Response, Self::Error>;
                fn poll_ready(
                    &mut self,
                    _cx: &mut Context<'_>,
                ) -> Poll<std::result::Result<(), Self::Error>> {
                    Poll::Ready(Ok(()))
                }
                fn call(&mut self, req: http::Request<B>) -> Self::Future {
                    match req.uri().path() {
                        "/systemtest.v1.CoordinatorPlugin/DescribePlugin" => {
                            #[allow(non_camel_case_types)]
                            struct DescribePluginSvc<T: CoordinatorPlugin>(pub Arc<T>);
                            impl<T: CoordinatorPlugin> tonic::server::UnaryService<super::Empty> for DescribePluginSvc<T> {
                                type Response = super::DescribeResponses;
                                type Future =
                                    BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                                fn call(
                                    &mut self,
                                    request: tonic::Request<super::Empty>,
                                ) -> Self::Future {
                                    let inner = Arc::clone(&self.0);
                                    let fut = async move {
                                        <T as CoordinatorPlugin>::describe_plugin(&inner, request)
                                            .await
                                    };
                                    Box::pin(fut)
                                }
                            }
                            let accept_compression_encodings = self.accept_compression_encodings;
                            let send_compression_encodings = self.send_compression_encodings;
                            let max_decoding_message_size = self.max_decoding_message_size;
                            let max_encoding_message_size = self.max_encoding_message_size;
                            let inner = self.inner.clone();
                            let fut = async move {
                                let method = DescribePluginSvc(inner);
                                let codec = tonic::codec::ProstCodec::default();
                                let mut grpc = tonic::server::Grpc::new(codec)
                                    .apply_compression_config(
                                        accept_compression_encodings,
                                        send_compression_encodings,
                                    )
                                    .apply_max_message_size_config(
                                        max_decoding_message_size,
                                        max_encoding_message_size,
                                    );
                                let res = grpc.unary(method, req).await;
                                Ok(res)
                            };
                            Box::pin(fut)
                        }
                        "/systemtest.v1.CoordinatorPlugin/GetResourcePool" => {
                            #[allow(non_camel_case_types)]
                            struct GetResourcePoolSvc<T: CoordinatorPlugin>(pub Arc<T>);
                            impl<T: CoordinatorPlugin>
                                tonic::server::UnaryService<super::CreateRequest>
                                for GetResourcePoolSvc<T>
                            {
                                type Response = super::ResourcePool;
                                type Future =
                                    BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                                fn call(
                                    &mut self,
                                    request: tonic::Request<super::CreateRequest>,
                                ) -> Self::Future {
                                    let inner = Arc::clone(&self.0);
                                    let fut = async move {
                                        <T as CoordinatorPlugin>::get_resource_pool(&inner, request)
                                            .await
                                    };
                                    Box::pin(fut)
                                }
                            }
                            let accept_compression_encodings = self.accept_compression_encodings;
                            let send_compression_encodings = self.send_compression_encodings;
                            let max_decoding_message_size = self.max_decoding_message_size;
                            let max_encoding_message_size = self.max_encoding_message_size;
                            let inner = self.inner.clone();
                            let fut = async move {
                                let method = GetResourcePoolSvc(inner);
                                let codec = tonic::codec::ProstCodec::default();
                                let mut grpc = tonic::server::Grpc::new(codec)
                                    .apply_compression_config(
                                        accept_compression_encodings,
                                        send_compression_encodings,
                                    )
                                    .apply_max_message_size_config(
                                        max_decoding_message_size,
                                        max_encoding_message_size,
                                    );
                                let res = grpc.unary(method, req).await;
                                Ok(res)
                            };
                            Box::pin(fut)
                        }
                        "/systemtest.v1.CoordinatorPlugin/GetResourceRequests" => {
                            #[allow(non_camel_case_types)]
                            struct GetResourceRequestsSvc<T: CoordinatorPlugin>(pub Arc<T>);
                            impl<T: CoordinatorPlugin>
                                tonic::server::UnaryService<super::CreateRequest>
                                for GetResourceRequestsSvc<T>
                            {
                                type Response = super::ResourceRequests;
                                type Future =
                                    BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                                fn call(
                                    &mut self,
                                    request: tonic::Request<super::CreateRequest>,
                                ) -> Self::Future {
                                    let inner = Arc::clone(&self.0);
                                    let fut = async move {
                                        <T as CoordinatorPlugin>::get_resource_requests(
                                            &inner, request,
                                        )
                                        .await
                                    };
                                    Box::pin(fut)
                                }
                            }
                            let accept_compression_encodings = self.accept_compression_encodings;
                            let send_compression_encodings = self.send_compression_encodings;
                            let max_decoding_message_size = self.max_decoding_message_size;
                            let max_encoding_message_size = self.max_encoding_message_size;
                            let inner = self.inner.clone();
                            let fut = async move {
                                let method = GetResourceRequestsSvc(inner);
                                let codec = tonic::codec::ProstCodec::default();
                                let mut grpc = tonic::server::Grpc::new(codec)
                                    .apply_compression_config(
                                        accept_compression_encodings,
                                        send_compression_encodings,
                                    )
                                    .apply_max_message_size_config(
                                        max_decoding_message_size,
                                        max_encoding_message_size,
                                    );
                                let res = grpc.unary(method, req).await;
                                Ok(res)
                            };
                            Box::pin(fut)
                        }
                        "/systemtest.v1.CoordinatorPlugin/CreateFixture" => {
                            #[allow(non_camel_case_types)]
                            struct CreateFixtureSvc<T: CoordinatorPlugin>(pub Arc<T>);
                            impl<T: CoordinatorPlugin>
                                tonic::server::ServerStreamingService<super::CreateRequest>
                                for CreateFixtureSvc<T>
                            {
                                type Response = super::CreateProgress;
                                type ResponseStream = T::CreateFixtureStream;
                                type Future =
                                    BoxFuture<tonic::Response<Self::ResponseStream>, tonic::Status>;
                                fn call(
                                    &mut self,
                                    request: tonic::Request<super::CreateRequest>,
                                ) -> Self::Future {
                                    let inner = Arc::clone(&self.0);
                                    let fut = async move {
                                        <T as CoordinatorPlugin>::create_fixture(&inner, request)
                                            .await
                                    };
                                    Box::pin(fut)
                                }
                            }
                            let accept_compression_encodings = self.accept_compression_encodings;
                            let send_compression_encodings = self.send_compression_encodings;
                            let max_decoding_message_size = self.max_decoding_message_size;
                            let max_encoding_message_size = self.max_encoding_message_size;
                            let inner = self.inner.clone();
                            let fut = async move {
                                let method = CreateFixtureSvc(inner);
                                let codec = tonic::codec::ProstCodec::default();
                                let mut grpc = tonic::server::Grpc::new(codec)
                                    .apply_compression_config(
                                        accept_compression_encodings,
                                        send_compression_encodings,
                                    )
                                    .apply_max_message_size_config(
                                        max_decoding_message_size,
                                        max_encoding_message_size,
                                    );
                                let res = grpc.server_streaming(method, req).await;
                                Ok(res)
                            };
                            Box::pin(fut)
                        }
                        "/systemtest.v1.CoordinatorPlugin/DestroyFixture" => {
                            #[allow(non_camel_case_types)]
                            struct DestroyFixtureSvc<T: CoordinatorPlugin>(pub Arc<T>);
                            impl<T: CoordinatorPlugin>
                                tonic::server::UnaryService<super::DestroyRequest>
                                for DestroyFixtureSvc<T>
                            {
                                type Response = super::DestroyResponse;
                                type Future =
                                    BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                                fn call(
                                    &mut self,
                                    request: tonic::Request<super::DestroyRequest>,
                                ) -> Self::Future {
                                    let inner = Arc::clone(&self.0);
                                    let fut = async move {
                                        <T as CoordinatorPlugin>::destroy_fixture(&inner, request)
                                            .await
                                    };
                                    Box::pin(fut)
                                }
                            }
                            let accept_compression_encodings = self.accept_compression_encodings;
                            let send_compression_encodings = self.send_compression_encodings;
                            let max_decoding_message_size = self.max_decoding_message_size;
                            let max_encoding_message_size = self.max_encoding_message_size;
                            let inner = self.inner.clone();
                            let fut = async move {
                                let method = DestroyFixtureSvc(inner);
                                let codec = tonic::codec::ProstCodec::default();
                                let mut grpc = tonic::server::Grpc::new(codec)
                                    .apply_compression_config(
                                        accept_compression_encodings,
                                        send_compression_encodings,
                                    )
                                    .apply_max_message_size_config(
                                        max_decoding_message_size,
                                        max_encoding_message_size,
                                    );
                                let res = grpc.unary(method, req).await;
                                Ok(res)
                            };
                            Box::pin(fut)
                        }
                        "/systemtest.v1.CoordinatorPlugin/HealthCheck" => {
                            #[allow(non_camel_case_types)]
                            struct HealthCheckSvc<T: CoordinatorPlugin>(pub Arc<T>);
                            impl<T: CoordinatorPlugin>
                                tonic::server::UnaryService<super::HealthCheckRequest>
                                for HealthCheckSvc<T>
                            {
                                type Response = super::HealthCheckResponse;
                                type Future =
                                    BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                                fn call(
                                    &mut self,
                                    request: tonic::Request<super::HealthCheckRequest>,
                                ) -> Self::Future {
                                    let inner = Arc::clone(&self.0);
                                    let fut = async move {
                                        <T as CoordinatorPlugin>::health_check(&inner, request)
                                            .await
                                    };
                                    Box::pin(fut)
                                }
                            }
                            let accept_compression_encodings = self.accept_compression_encodings;
                            let send_compression_encodings = self.send_compression_encodings;
                            let max_decoding_message_size = self.max_decoding_message_size;
                            let max_encoding_message_size = self.max_encoding_message_size;
                            let inner = self.inner.clone();
                            let fut = async move {
                                let method = HealthCheckSvc(inner);
                                let codec = tonic::codec::ProstCodec::default();
                                let mut grpc = tonic::server::Grpc::new(codec)
                                    .apply_compression_config(
                                        accept_compression_encodings,
                                        send_compression_encodings,
                                    )
                                    .apply_max_message_size_config(
                                        max_decoding_message_size,
                                        max_encoding_message_size,
                                    );
                                let res = grpc.unary(method, req).await;
                                Ok(res)
                            };
                            Box::pin(fut)
                        }
                        _ => Box::pin(async move {
                            let mut response = http::Response::new(empty_body());
                            let headers = response.headers_mut();
                            headers.insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                            headers.insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                            Ok(response)
                        }),
                    }
                }
            }
            impl<T> Clone for CoordinatorPluginServer<T> {
                fn clone(&self) -> Self {
                    let inner = self.inner.clone();
                    Self {
                        inner,
                        accept_compression_encodings: self.accept_compression_encodings,
                        send_compression_encodings: self.send_compression_encodings,
                        max_decoding_message_size: self.max_decoding_message_size,
                        max_encoding_message_size: self.max_encoding_message_size,
                    }
                }
            }
            /// Generated gRPC service name
            pub const SERVICE_NAME: &str = "systemtest.v1.CoordinatorPlugin";
            impl<T> tonic::server::NamedService for CoordinatorPluginServer<T> {
                const NAME: &'static str = SERVICE_NAME;
            }
        }
    }
}
